"""Module to keep track of overworld exits (ow exit rando?)"""
from dataclasses import dataclass
import enum

from ctrando.common import ctenums


@dataclass
class OWExitInfo:
    overworld_id: ctenums.OverWorldID
    exit_id: int


class OWExitEnum(enum.Enum):
    ## Present, 0x50 exits
    VORTEX_PT = OWExitInfo(ctenums.OverWorldID.PRESENT, 0)
    NORTHERN_RUINS_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 1)
    HEROS_GRAVE_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 2)
    FIONAS_SHRINE = OWExitInfo(ctenums.OverWorldID.PRESENT, 3)
    CRONOS_HOUSE = OWExitInfo(ctenums.OverWorldID.PRESENT, 4)
    TRUCE_SINGLE_RESIDENCE = OWExitInfo(ctenums.OverWorldID.PRESENT, 5)
    TRUCE_INN_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 6)
    TRUCE_TICKET_OFFICE = OWExitInfo(ctenums.OverWorldID.PRESENT, 7)
    TRUCE_SCREAMING_RESIDENCE = OWExitInfo(ctenums.OverWorldID.PRESENT, 8)
    MILLENNIAL_FAIR = OWExitInfo(ctenums.OverWorldID.PRESENT, 9)
    TRUCE_MARKET_1000_NE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xA)
    TRUCE_MAYOR = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xB)
    LUCCAS_HOUSE_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xC)
    GUARDIA_CASTLE_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xD)
    GUARDIA_FOREST_SOUTH = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xE)
    GUARDIA_FOREST_NORTH = OWExitInfo(ctenums.OverWorldID.PRESENT, 0xF)
    ZENAN_BRIDGE_1000_NORTH = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x10)
    ZENAN_BRIDGE_1000_SOUTH = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x11)
    PORRE_INN_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x12)
    PORRE_MARKET_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x13)
    SNAIL_STOP = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x14)
    PORRE_MAYOR_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x15)
    PORRE_RESIDENCE_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x16)
    PORRE_TICKET_OFFICE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x17)
    MEDINA_ELDER_HOUSE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x18)
    MEDINA_INN_WEIRD = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x19)
    MEDINA_PORTAL = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1A)
    MELCHIORS_HUT = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1B)
    MELCHIORS_HUT_SW  = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1C)
    MEDINA_MARKET = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1D)
    MEDINA_SQUARE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1E)
    MEDINA_SQUARE_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x1F)
    MEDINA_SQUARE_E = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x20)
    MEDINA_SQUARE_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x21)
    CHORAS_MAYOR_1000_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x22)
    CHORAS_CARPENTER_1000_N = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x23)
    CHORAS_INN_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x24)
    FOREST_RUINS = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x25)
    HECKRAN_CAVE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x26)
    SUN_KEEP_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x27)
    TRUCE_MAYOR_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x28)
    TRUCE_MAYOR_SW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x29)
    TRUCE_SCREAMING_RESIDENCE_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2A)
    TRUCE_SCREAMING_RESIDENCE_NE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2B)
    TRUCE_MARKET_1000_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2C)
    TRUCE_SINGLE_RESIDENCE_N = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2D)
    TRUCE_INN_1000_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2E)
    LUCCAS_HOUSE_SW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x2F)
    LUCCAS_HOUSE_SE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x30)
    LUCCAS_HOUSE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x31)
    LUCCAS_HOUSE_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x32)
    LUCCAS_HOUSE_E = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x33)
    TRUCE_MARKET_1000_SE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x34)
    SNAIL_STOP_NW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x35)
    SNAIL_STOP_N = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x36)
    PORRE_RESIDENCE_1000_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x37)
    CHORAS_INN_1000_NW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x38)
    CHORAS_INN_1000_N = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x39)
    CHORAS_CARPENTER_1000_NW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3A)
    CHORAS_CARPENTER_1000_NE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3B)
    CHORAS_MAYOR_1000_SW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3C)
    CHORAS_MAYOR_1000_SE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3D)
    CHORAS_MAYOR_1000_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3E)
    CHORAS_MAYOR_1000 = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x3F)
    CHORAS_MAYOR_1000_E = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x40)
    MEDINA_ELDER_HOUSE_E = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x41)
    MEDINA_ELDER_HOUSE_NE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x42)
    MEDINA_INN_NW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x43)
    MEDINA_INN_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x44)
    MEDINA_INN_N = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x45)
    MEDINA_PORTAL_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x46)
    MEDINA_PORTAL_SE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x47)
    MELCHIORS_HUT_E = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x48)
    MELCHIORS_HUT_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x49)
    MELCHIORS_HUT_S = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4A)
    MELCHIORS_HUT_SE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4B)
    MEDINA_MARKET_NW = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4C)
    MEDINA_MARKET_W = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4D)
    MEDINA_MARKET_NE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4E)
    WEST_CAPE = OWExitInfo(ctenums.OverWorldID.PRESENT, 0x4F)
    # Middle Ages - 0x4A exits
    ZENAN_BRIDGE_WRECKED = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0)
    ZENAN_BRIDGE_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 1)
    ZENAN_BRIDGE_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 2)
    MAGIC_CAVE_CLOSED = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 3)
    MAGIC_CAVE_OPEN = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 4)
    SUNKEN_DESERT_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 5)
    SUNKEN_DESERT_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 6)
    NORTHERN_RUINS_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 7)
    HEROS_GRAVE_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 8)
    MAGUS_LAIR = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 9)
    GIANTS_CLAW_CLOSED = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xA)
    GIANTS_CLAW_OPEN = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xB)
    TRUCE_CANYON = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xC)
    TRUCE_COUPLE_RESISDENCE_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xD)
    TRUCE_SMITH_RESIDENCE_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xE)
    TRUCE_INN_600_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0xF)
    TRUCE_MARKET_600_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x10)
    GUARDIA_FOREST_600_SOUTH = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x11)
    GUARDIA_FOREST_600_NORTH = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x12)
    GUARDIA_CASTLE_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x13)
    MANORIA_CATHEDRAL = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x14)
    DORINO_BROMIDE_RESIDENCE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x15)
    DORINO_ELDER_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x16)
    DORINO_INN_W =  OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x17)
    DORINO_MARKET_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x18)
    TATAS_HOUSE_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x19)
    PORRE_ELDER_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1A)
    PORRE_CAFE_600_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1B)
    PORRE_INN_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1C)
    PORRE_MARKET_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1D)
    FIONAS_VILLA_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1E)
    FIONAS_VILLA_SW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x1F)
    FIONAS_VILLA_SE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x20)
    FIONAS_VILLA = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x21)
    FIONAS_VILLA_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x22)
    FIONAS_VILLA_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x23)
    CHORAS_OLD_RESIDENCE_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x24)
    CHORAS_INN_600_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x25)
    CHORAS_CAFE_600_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x26)
    CHORAS_CARPENTER_600_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x27)
    CHORAS_MARKET_600_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x28)
    CURSED_WOODS = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x29)
    DENADORO_MTS = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2A)
    MAGIC_CAVE_MAGUS = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2B)
    OZZIES_FORT = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2C)
    SUN_KEEP_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2D)
    TRUCE_COUPLE_RESISDENCE_600_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2E)
    TRUCE_SMITH_RESIDENCE_600_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x2F)
    TRUCE_SMITH_RESIDENCE_600_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x30)
    TRUCE_INN_600_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x31)
    TRUCE_MARKET_600_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x32)
    TRUCE_MARKET_600_SE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x33)
    DORINO_BROMIDE_RESIDENCE_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x34)
    DORINO_ELDER_NE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x35)
    DORINO_ELDER = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x36)
    DORINO_INN_NW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x37)
    DORINO_INN_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x38)
    DORINO_MARKET_S = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x39)
    DORINO_MARKET_SE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3A)
    TATAS_HOUSE_NE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3B)
    TATAS_HOUSE_NW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3C)
    PORRE_CAFE_600_NW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3D)
    PORRE_CAFE_600_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3E)
    CHORAS_OLD_RESIDENCE_600_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x3F)
    CHORAS_INN_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x40)
    CHORAS_INN_600_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x41)
    CHORAS_CAFE_600_NW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x42)
    CHORAS_CAFE_600_N = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x43)
    CHORAS_CARPENTER_600_NE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x44)
    CHORAS_CARPENTER_600_NW = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x45)
    CHORAS_MARKET_600_SE = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x46)
    CHORAS_MARKET_600_E = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x47)
    CHORAS_MARKET_600 = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x48)
    CHORAS_MARKET_600_W = OWExitInfo(ctenums.OverWorldID.MIDDLE_AGES, 0x49)
    # Future - 0x14 Exits
    TRANN_DOME = OWExitInfo(ctenums.OverWorldID.FUTURE, 0)
    TRANN_DOME_E = OWExitInfo(ctenums.OverWorldID.FUTURE, 1)
    BANGOR_DOME = OWExitInfo(ctenums.OverWorldID.FUTURE, 2)
    ARRIS_DOME_E = OWExitInfo(ctenums.OverWorldID.FUTURE, 3)
    ARRIS_DOME_W = OWExitInfo(ctenums.OverWorldID.FUTURE, 4)
    PROTO_DOME_E = OWExitInfo(ctenums.OverWorldID.FUTURE, 5)
    PROTO_DOME_W = OWExitInfo(ctenums.OverWorldID.FUTURE, 6)
    KEEPERS_DOME_E = OWExitInfo(ctenums.OverWorldID.FUTURE, 7)
    KEEPERS_DOME_W = OWExitInfo(ctenums.OverWorldID.FUTURE, 8)
    FACTORY_RUINS = OWExitInfo(ctenums.OverWorldID.FUTURE, 9)
    LAB_16_WEST = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xA)
    LAB_16_EAST = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xB)
    LAB_32_WEST = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xC)
    LAB_32_EAST = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xD)
    SEWER_ACCESS_ARRIS = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xE)
    SEWER_ACCESS_KEEPERS = OWExitInfo(ctenums.OverWorldID.FUTURE, 0xF)
    SUN_KEEP_2300 = OWExitInfo(ctenums.OverWorldID.FUTURE, 0x10)
    GENO_DOME = OWExitInfo(ctenums.OverWorldID.FUTURE, 0x11)
    DEATH_PEAK = OWExitInfo(ctenums.OverWorldID.FUTURE, 0x12)
    SUN_PALACE = OWExitInfo(ctenums.OverWorldID.FUTURE, 0x13)
    # Prehistory - 0x19 Exits
    MYSTIC_MTS = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0)
    TYRANO_LAIR = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 1)
    FOREST_MAZE_LOCKED_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 2)
    FOREST_MAZE_LOCKED_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 3)
    FOREST_MAZE_LOCKED_SOUTH_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 4)
    FOREST_MAZE_LOCKED_SOUTH_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 5)
    FOREST_MAZE_NORTH_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 6)
    FOREST_MAZE_NORTH_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 7)
    FOREST_MAZE_SOUTH_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 8)
    FOREST_MAZE_SOUTH_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 9)
    REPTITE_LAIR_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xA)
    REPTITE_LAIR_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xB)
    DACTYL_NEST = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xC)
    SUN_KEEP_PREHISTORY = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xD)
    IOKA_MEETING_SOUTH = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xE)
    CHIEFS_HUT = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0xF)
    TRADING_POST = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x10)
    IOKA_SW_HUT = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x11)
    IOKA_SWEET_WATER_HUT = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x12)
    HUNTING_RANGE = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x13)
    IOKA_MEETING_NORTH = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x14)
    LARUBA_RUINS = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x15)
    LAIR_RUINS_W = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x16)
    LAIR_RUINS = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x17)
    LAIR_RUINS_E = OWExitInfo(ctenums.OverWorldID.PREHISTORY, 0x18)
    # Dark Ages - 7 Exits
    TERRA_CAVE = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 0)
    SKYWAY_ENHASA_SOUTH = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 1)
    SKYWAY_ENHASA_NORTH = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 2)
    SKYWAY_KAJAR = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 3)
    DARK_AGES_PORTAL = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 4)
    # Exits for after woe falls if you go through the Beast Cave
    BEAST_CAVE_UNUSED_E = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 5)
    BEAST_CAVE_UNUSED_W = OWExitInfo(ctenums.OverWorldID.DARK_AGES, 6)
    # Zeal - 0xE Exits
    ZEAL_TELEPORTER_1 = OWExitInfo(ctenums.OverWorldID.ZEAL, 0)
    ZEAL_TELEPORTER_2_UNUSED = OWExitInfo(ctenums.OverWorldID.ZEAL, 1)
    ZEAL_TELEPORTER_4 = OWExitInfo(ctenums.OverWorldID.ZEAL, 2)
    ZEAL_TELEPORTER_3_UNUSED = OWExitInfo(ctenums.OverWorldID.ZEAL, 3)
    ZEAL_TELEPORTER_FAKE = OWExitInfo(ctenums.OverWorldID.ZEAL, 4)
    ZEAL_PALACE = OWExitInfo(ctenums.OverWorldID.ZEAL, 5)
    ENHASA = OWExitInfo(ctenums.OverWorldID.ZEAL, 6)
    ENHASA_E = OWExitInfo(ctenums.OverWorldID.ZEAL, 7)
    LAND_BRIGE_ENHASA_SOUTH = OWExitInfo(ctenums.OverWorldID.ZEAL, 8)
    KAJAR = OWExitInfo(ctenums.OverWorldID.ZEAL, 9)
    LAND_BRIGE_KAJAR = OWExitInfo(ctenums.OverWorldID.ZEAL, 0xA)
    LAND_BRIGE_ENHASA_NORTH = OWExitInfo(ctenums.OverWorldID.ZEAL, 0xB)
    BLACKBIRD_S = OWExitInfo(ctenums.OverWorldID.ZEAL, 0xC)
    BLACKBIRD_N = OWExitInfo(ctenums.OverWorldID.ZEAL, 0xD)
    # Last Village - 7 Exits
    NORTH_CAPE = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 0)
    LAST_VILLAGE_COMMONS = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 1)
    LAST_VILLAGE_EMPTY_HUT = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 2)
    LAST_VILLAGE_SHOP = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 3)
    LAST_VILLAGE_RESIDENCE = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 4)
    SUN_KEEP_LAST_VILLAGE = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 5)
    LAST_VILLAGE_PORTAL = OWExitInfo(ctenums.OverWorldID.LAST_VILLAGE, 6)


class OWExitClass(enum.Enum):
    # Present
    VORTEX_PT = (OWExitEnum.VORTEX_PT,)
    NORTHERN_RUINS_1000 = (OWExitEnum.NORTHERN_RUINS_1000, OWExitEnum.HEROS_GRAVE_1000)
    FIONAS_SHRINE = (OWExitEnum.FIONAS_SHRINE,)
    CRONOS_HOUSE = (OWExitEnum.CRONOS_HOUSE,)
    TRUCE_SINGLE_RESIDENCE = (OWExitEnum.TRUCE_SINGLE_RESIDENCE,
                              OWExitEnum.TRUCE_SINGLE_RESIDENCE_N)
    TRUCE_INN_1000 = (OWExitEnum.TRUCE_INN_1000,
                      OWExitEnum.TRUCE_INN_1000_S)
    TRUCE_TICKET_OFFICE = (OWExitEnum.TRUCE_TICKET_OFFICE,)
    TRUCE_SCREAMING_RESIDENCE = (OWExitEnum.TRUCE_SCREAMING_RESIDENCE,
                                 OWExitEnum.TRUCE_SCREAMING_RESIDENCE_W,
                                 OWExitEnum.TRUCE_SCREAMING_RESIDENCE_NE)
    MILLENNIAL_FAIR = (OWExitEnum.MILLENNIAL_FAIR,)
    TRUCE_MARKET_1000 = (OWExitEnum.TRUCE_MARKET_1000_SE,
                         OWExitEnum.TRUCE_MARKET_1000_NE,
                         OWExitEnum.TRUCE_MARKET_1000_S)
    TRUCE_MAYOR = (OWExitEnum.TRUCE_MAYOR_S, OWExitEnum.TRUCE_MAYOR_SW,
                   OWExitEnum.TRUCE_MAYOR)
    LUCCAS_HOUSE = (OWExitEnum.LUCCAS_HOUSE, OWExitEnum.LUCCAS_HOUSE_E,
                    OWExitEnum.LUCCAS_HOUSE_SE, OWExitEnum.LUCCAS_HOUSE_S,
                    OWExitEnum.LUCCAS_HOUSE_SW, OWExitEnum.LUCCAS_HOUSE_W)
    GUARDIA_CASTLE_1000 = (OWExitEnum.GUARDIA_CASTLE_1000,)
    GUARDIA_FOREST_SOUTH_1000 = (OWExitEnum.GUARDIA_FOREST_SOUTH,)
    GUARDIA_FOREST_NORTH_1000 = (OWExitEnum.GUARDIA_FOREST_NORTH,)
    ZENAN_BRIDGE_1000_NORTH = (OWExitEnum.ZENAN_BRIDGE_1000_NORTH,)
    ZENAN_BRIDGE_1000_SOUTH = (OWExitEnum.ZENAN_BRIDGE_1000_SOUTH,)
    PORRE_INN_1000 = (OWExitEnum.PORRE_INN_1000,)
    PORRE_MARKET_1000 = (OWExitEnum.PORRE_MARKET_1000,)
    SNAIL_STOP = (OWExitEnum.SNAIL_STOP, OWExitEnum.SNAIL_STOP_N,
                  OWExitEnum.SNAIL_STOP_NW,)
    PORRE_MAYOR_1000 = (OWExitEnum.PORRE_MAYOR_1000,)
    PORRE_RESIDENCE_1000 = (OWExitEnum.PORRE_RESIDENCE_1000,
                            OWExitEnum.PORRE_RESIDENCE_1000_W)
    PORRE_TICKET_OFFICE = (OWExitEnum.PORRE_TICKET_OFFICE,)
    MEDINA_ELDER_HOUSE = (OWExitEnum.MEDINA_ELDER_HOUSE,
                          OWExitEnum.MEDINA_ELDER_HOUSE_E,
                          OWExitEnum.MEDINA_ELDER_HOUSE_NE)
    MEDINA_INN = (OWExitEnum.MEDINA_INN_W, OWExitEnum.MEDINA_INN_N,
                  OWExitEnum.MEDINA_INN_NW)
    MEDINA_PORTAL = (OWExitEnum.MEDINA_PORTAL, OWExitEnum.MEDINA_PORTAL_S, OWExitEnum.MEDINA_PORTAL_SE)
    MELCHIORS_HUT = (OWExitEnum.MELCHIORS_HUT, OWExitEnum.MELCHIORS_HUT_E,
                     OWExitEnum.MELCHIORS_HUT_SE, OWExitEnum.MELCHIORS_HUT_S,
                     OWExitEnum.MELCHIORS_HUT_SW, OWExitEnum.MELCHIORS_HUT_W)
    MEDINA_MARKET = (OWExitEnum.MEDINA_MARKET_W, OWExitEnum.MEDINA_MARKET_NE,
                     OWExitEnum.MEDINA_MARKET_NW, OWExitEnum.MEDINA_MARKET)
    MEDINA_SQUARE = (OWExitEnum.MEDINA_SQUARE, OWExitEnum.MEDINA_SQUARE_E,
                     OWExitEnum.MEDINA_SQUARE_S, OWExitEnum.MEDINA_SQUARE_W)
    CHORAS_MAYOR_1000 = (OWExitEnum.CHORAS_MAYOR_1000, OWExitEnum.CHORAS_MAYOR_1000_E,
                         OWExitEnum.CHORAS_MAYOR_1000_SE, OWExitEnum.CHORAS_MAYOR_1000_S,
                         OWExitEnum.CHORAS_MAYOR_1000_SW, OWExitEnum.CHORAS_MAYOR_1000_W)
    CHORAS_INN_1000 = (OWExitEnum.CHORAS_INN_1000_NW, OWExitEnum.CHORAS_INN_1000_N,
                       OWExitEnum.CHORAS_INN_1000)
    CHORAS_CARPENTER_1000 = (OWExitEnum.CHORAS_CARPENTER_1000_NE, OWExitEnum.CHORAS_CARPENTER_1000_N,
                             OWExitEnum.CHORAS_CARPENTER_1000_NW)
    FOREST_RUINS = (OWExitEnum.FOREST_RUINS,)
    HECKRAN_CAVE = (OWExitEnum.HECKRAN_CAVE,)
    SUN_KEEP_1000 = (OWExitEnum.SUN_KEEP_1000,)
    WEST_CAPE = (OWExitEnum.WEST_CAPE,)
    # Middle Ages
    ZENAN_BRIDGE_600_NORTH = (OWExitEnum.ZENAN_BRIDGE_N,)
    ZENAN_BRIDGE_600_SOUTH = (OWExitEnum.ZENAN_BRIDGE_S,)
    MAGIC_CAVE_CLOSED = (OWExitEnum.MAGIC_CAVE_CLOSED,)
    MAGIC_CAVE_OPEN = (OWExitEnum.MAGIC_CAVE_OPEN,)
    SUNKEN_DESERT = (OWExitEnum.SUNKEN_DESERT_N, OWExitEnum.SUNKEN_DESERT_S)
    NORTHERN_RUINS_600 = (OWExitEnum.NORTHERN_RUINS_600, OWExitEnum.HEROS_GRAVE_600)
    MAGUS_LAIR = (OWExitEnum.MAGUS_LAIR,)
    GIANTS_CLAW = (OWExitEnum.GIANTS_CLAW_OPEN,)
    TRUCE_CANYON = (OWExitEnum.TRUCE_CANYON,)
    TRUCE_COUPLE_RESIDENCE_600 = (OWExitEnum.TRUCE_COUPLE_RESISDENCE_600,
                                  OWExitEnum.TRUCE_COUPLE_RESISDENCE_600_E)
    TRUCE_SMITH_RESIDENCE = (OWExitEnum.TRUCE_SMITH_RESIDENCE_600,
                             OWExitEnum.TRUCE_SMITH_RESIDENCE_600_W,
                             OWExitEnum.TRUCE_SMITH_RESIDENCE_600_E)
    TRUCE_INN_600 = (OWExitEnum.TRUCE_INN_600_N, OWExitEnum.TRUCE_INN_600_W)
    TRUCE_MARKET_600 = (OWExitEnum.TRUCE_MARKET_600_E, OWExitEnum.TRUCE_MARKET_600_S,
                        OWExitEnum.TRUCE_MARKET_600_SE)
    GUARDIA_FOREST_NORTH_600 = (OWExitEnum.GUARDIA_FOREST_600_NORTH,)
    GUARDIA_FOREST_SOUTH_600 = (OWExitEnum.GUARDIA_FOREST_600_SOUTH,)
    GUARDIA_CASTLE_600 = (OWExitEnum.GUARDIA_CASTLE_600,)
    MANORIA_CATHEDRAL = (OWExitEnum.MANORIA_CATHEDRAL,)
    DORINO_BROMIDE_RESIDENCE = (OWExitEnum.DORINO_BROMIDE_RESIDENCE,
                                OWExitEnum.DORINO_BROMIDE_RESIDENCE_E)
    DORINO_ELDER = (OWExitEnum.DORINO_ELDER, OWExitEnum.DORINO_ELDER_NE,
                    OWExitEnum.DORINO_ELDER_N)
    DORINO_INN = (OWExitEnum.DORINO_INN_W, OWExitEnum.DORINO_INN_N,
                  OWExitEnum.DORINO_INN_NW)
    DORINO_MARKET = (OWExitEnum.DORINO_MARKET_SE, OWExitEnum.DORINO_MARKET_S,
                     OWExitEnum.DORINO_MARKET_E)
    TATAS_HOUSE = (OWExitEnum.TATAS_HOUSE_N, OWExitEnum.TATAS_HOUSE_NE, OWExitEnum.TATAS_HOUSE_NW)
    PORRE_ELDER_600 = (OWExitEnum.PORRE_ELDER_600,)
    PORRE_CAFE_600 = (OWExitEnum.PORRE_CAFE_600_NW, OWExitEnum.PORRE_CAFE_600_N,
                      OWExitEnum.PORRE_CAFE_600_W)
    PORRE_INN_600 = (OWExitEnum.PORRE_INN_600,)
    PORRE_MARKET_600 = (OWExitEnum.PORRE_MARKET_600,)
    FIONAS_VILLA = (OWExitEnum.FIONAS_VILLA, OWExitEnum.FIONAS_VILLA_E,
                    OWExitEnum.FIONAS_VILLA_SE, OWExitEnum.FIONAS_VILLA_S,
                    OWExitEnum.FIONAS_VILLA_SW, OWExitEnum.FIONAS_VILLA_W)
    CHORAS_OLD_RESIDENCE_600 = (OWExitEnum.CHORAS_OLD_RESIDENCE_600_N,
                                OWExitEnum.CHORAS_OLD_RESIDENCE_600)
    CHORAS_INN_600 = (OWExitEnum.CHORAS_INN_600, OWExitEnum.CHORAS_INN_600_E,
                      OWExitEnum.CHORAS_INN_600_S)
    CHORAS_CAFE_600 = (OWExitEnum.CHORAS_CAFE_600_NW, OWExitEnum.CHORAS_CAFE_600_N,
                       OWExitEnum.CHORAS_CAFE_600_W)
    CHORAS_CARPENTER_600 = (OWExitEnum.CHORAS_CARPENTER_600_NE, OWExitEnum.CHORAS_CARPENTER_600_N,
                            OWExitEnum.CHORAS_CARPENTER_600_NW)
    CHORAS_MARKET_600 = (OWExitEnum.CHORAS_MARKET_600_E, OWExitEnum.CHORAS_MARKET_600_SE,
                         OWExitEnum.CHORAS_MARKET_600_S, OWExitEnum.CHORAS_MARKET_600_W)
    CURSED_WOODS = (OWExitEnum.CURSED_WOODS,)
    DENADORO_MTS = (OWExitEnum.DENADORO_MTS,)
    MAGIC_CAVE_MAGUS = (OWExitEnum.MAGIC_CAVE_MAGUS,)
    OZZIES_FORT = (OWExitEnum.OZZIES_FORT,)
    SUN_KEEP_600 = (OWExitEnum.SUN_KEEP_600,)
    # Future
    TRANN_DOME = (OWExitEnum.TRANN_DOME, OWExitEnum.TRANN_DOME_E)
    BANGOR_DOME = (OWExitEnum.BANGOR_DOME,)
    ARRIS_DOME = (OWExitEnum.ARRIS_DOME_W, OWExitEnum.ARRIS_DOME_E)
    PROTO_DOME = (OWExitEnum.PROTO_DOME_W, OWExitEnum.PROTO_DOME_E)
    KEEPERS_DOME = (OWExitEnum.KEEPERS_DOME_W, OWExitEnum.KEEPERS_DOME_E)
    FACTORY_RUINS = (OWExitEnum.FACTORY_RUINS,)
    LAB_16_WEST = (OWExitEnum.LAB_16_WEST,)
    LAB_16_EAST = (OWExitEnum.LAB_16_EAST,)
    LAB_32_WEST = (OWExitEnum.LAB_32_WEST,)
    LAB_32_EAST = (OWExitEnum.LAB_32_EAST,)
    SEWER_ACCESS_ARRIS = (OWExitEnum.SEWER_ACCESS_ARRIS,)
    SEWER_ACCESS_KEEPERS = (OWExitEnum.SEWER_ACCESS_KEEPERS,)
    SUN_KEEP_2300 = (OWExitEnum.SUN_KEEP_2300,)
    GENO_DOME = (OWExitEnum.GENO_DOME,)
    DEATH_PEAK = (OWExitEnum.DEATH_PEAK,)
    SUN_PALACE = (OWExitEnum.SUN_PALACE,)
    # Prehistory
    MYSTIC_MTS = (OWExitEnum.MYSTIC_MTS,)
    TYRANO_LAIR = (OWExitEnum.TYRANO_LAIR,)
    # Skip locked forest maze
    FOREST_MAZE_NORTH = (OWExitEnum.FOREST_MAZE_NORTH_E, OWExitEnum.FOREST_MAZE_NORTH_W)
    FOREST_MAZE_SOUTH = (OWExitEnum.FOREST_MAZE_SOUTH_E, OWExitEnum.FOREST_MAZE_SOUTH_W)
    REPTITE_LAIR = (OWExitEnum.REPTITE_LAIR_W, OWExitEnum.REPTITE_LAIR_E)
    DACTYL_NEST = (OWExitEnum.DACTYL_NEST,)
    SUN_KEEP_PREHISTORY = (OWExitEnum.SUN_KEEP_PREHISTORY,)
    IOKA_MEETING_SOUTH = (OWExitEnum.IOKA_MEETING_SOUTH,)
    IOKA_MEETING_NORTH = (OWExitEnum.IOKA_MEETING_NORTH,)
    CHIEFS_HUT = (OWExitEnum.CHIEFS_HUT,)
    TRADING_POST = (OWExitEnum.TRADING_POST,)
    IOKA_SW_HUT = (OWExitEnum.IOKA_SW_HUT,)
    IOKA_SWEET_WATER_HUT = (OWExitEnum.IOKA_SWEET_WATER_HUT,)
    HUNTING_RANGE = (OWExitEnum.HUNTING_RANGE,)
    LARUBA_RUINS = (OWExitEnum.LARUBA_RUINS,)
    LAIR_RUINS = (OWExitEnum.LAIR_RUINS, OWExitEnum.LAIR_RUINS_E,
                  OWExitEnum.LAIR_RUINS_W)
    # Dark Ages
    TERRA_CAVE = (OWExitEnum.TERRA_CAVE,)
    SKYWAY_ENHASA_SOUTH = (OWExitEnum.SKYWAY_ENHASA_SOUTH,)
    SKYWAY_ENHASA_NORTH = (OWExitEnum.SKYWAY_ENHASA_NORTH,)
    SKYWAY_KAJAR = (OWExitEnum.SKYWAY_KAJAR,)
    DARK_AGES_PORTAL = (OWExitEnum.DARK_AGES_PORTAL,)
    # Zeal
    ZEAL_TELEPORTER_BOTTOM = (OWExitEnum.ZEAL_TELEPORTER_1,)
    ZEAL_TELEPORTER_TOP = (OWExitEnum.ZEAL_TELEPORTER_4,)
    ZEAL_PALACE = (OWExitEnum.ZEAL_PALACE,)
    ENHASA = (OWExitEnum.ENHASA_E, OWExitEnum.ENHASA)
    LAND_BRIDGE_ENHASA_NORTH = (OWExitEnum.LAND_BRIGE_ENHASA_NORTH,)
    LAND_BRIDGE_ENHASA_SOUTH = (OWExitEnum.LAND_BRIGE_ENHASA_SOUTH,)
    LAND_BRIDGE_KAJAR = (OWExitEnum.LAND_BRIGE_KAJAR,)
    KAJAR = (OWExitEnum.KAJAR,)
    BLACKBIRD = (OWExitEnum.BLACKBIRD_N, OWExitEnum.BLACKBIRD_S)
    # Last Village
    NORTH_CAPE = (OWExitEnum.NORTH_CAPE,)
    LAST_VILLAGE_COMMONS = (OWExitEnum.LAST_VILLAGE_COMMONS,)
    LAST_VILLAGE_EMPTY_HUT = (OWExitEnum.LAST_VILLAGE_EMPTY_HUT,)
    LAST_VILLAGE_SHOP = (OWExitEnum.LAST_VILLAGE_SHOP,)
    LAST_VILLAGE_RESIDENCE = (OWExitEnum.LAST_VILLAGE_RESIDENCE,)
    SUN_KEEP_LAST_VILLAGE = (OWExitEnum.SUN_KEEP_LAST_VILLAGE,)
    LAST_VILLAGE_PORTAL = (OWExitEnum.LAST_VILLAGE_PORTAL,)


def get_era(ow_exit: OWExitClass) -> ctenums.OverWorldID:
    sample_exit = ow_exit.value[0]
    return sample_exit.value.overworld_id









