"""Module to hold useful enumerations of CT data."""
from enum import Enum, IntEnum, auto
from typing import TypeVar, Type

StrIntEnumT = TypeVar("StrIntEnumT", bound="StrIntEnum")


class StrIntEnum(IntEnum):
    """An enum that comes with some dicts for lookup"""

    def __str__(self):
        x = self.__repr__().split(".")[1].split(":")[0].lower().title()
        x = x.replace("_", " ")
        return x

    @classmethod
    def str_dict(cls: Type[StrIntEnumT]) -> dict[StrIntEnumT, str]:
        return dict((x, str(x)) for x in cls)

    @classmethod
    def inv_str_dict(cls: Type[StrIntEnumT]) -> dict[str, StrIntEnumT]:
        return dict((str(x), x) for x in cls)


class CharID(StrIntEnum):
    """Character index enumeration"""

    CRONO = 0
    MARLE = 1
    LUCCA = 2
    ROBO = 3
    FROG = 4
    AYLA = 5
    MAGUS = 6


class OverWorldID(StrIntEnum):
    """Overworld enumeration"""

    PRESENT = 0
    MIDDLE_AGES = 1
    FUTURE = 2
    PREHISTORY = 3
    DARK_AGES = 4
    ZEAL = 5
    LAST_VILLAGE = 6
    APOCALYPSE = 7


class LocID(StrIntEnum):
    """Location ID enumeration"""

    LOAD_SCREEN = 0x00
    CRONOS_KITCHEN = 0x01
    CRONOS_ROOM = 0x02
    LUCCAS_KITCHEN = 0x03
    LUCCAS_WORKSHOP = 0x04
    MILLENNIAL_FAIR = 0x05
    GATO_EXHIBIT = 0x06
    PREHISTORIC_EXHIBIT = 0x07
    TELEPOD_EXHIBIT = 0x08
    LARAS_ROOM = 0x09
    LUCCAS_ROOM = 0x0A
    ENDING_SELECTOR_00B = 0x0B
    TRUCE_INN_1000 = 0x0C
    TRUCE_MAYOR_1F = 0x0D
    TRUCE_MAYOR_2F = 0x0E
    TRUCE_SINGLE_WOMAN_RESIDENCE = 0x0F
    TRUCE_HAPPY_SCREAMING_COUPLE_RESIDENCE = 0x10
    TRUCE_MARKET = 0x11
    TRUCE_TICKET_OFFICE = 0x12
    GUARDIA_FOREST_1000 = 0x13
    GUARDIA_FOREST_DEAD_END = 0x14
    GUARDIA_THRONEROOM_1000 = 0x15
    KINGS_CHAMBER_1000 = 0x16
    QUEENS_ROOM_1000 = 0x17
    GUARDIA_KITCHEN_1000 = 0x18
    GUARDIA_BARRACKS_1000 = 0x19
    GUARDIA_BASEMENT = 0x1A
    COURTROOM = 0x1B
    PRISON_CATWALKS = 0x1C
    PRISON_SUPERVISORS_OFFICE = 0x1D
    PRISON_TORTURE_STORAGE_ROOM = 0x1E
    MEDINA_SQUARE = 0x1F
    ZENAN_BRIDGE_1000 = 0x20
    MEDINA_ELDER_1F = 0x21
    MEDINA_ELDER_2F = 0x22
    MEDINA_INN = 0x23
    MEDINA_PORTAL = 0x24
    ENDING_LEGENDARY_HERO = 0x25
    ELH_GUARDIA_THRONEROOM = 0x26
    MEDINA_MARKET = 0x27
    MELCHIORS_KITCHEN = 0x28
    MELCHIORS_WORKSHOP = 0x29
    FOREST_RUINS = 0x2A
    ETUP_CURSED_WOODS = 0x2B
    LEENE_SQUARE_2300 = 0x2C
    ELH_DENADORO = 0x2D
    ELH_MAGUS_THRONE_DEFENSE = 0x2E
    HECKRAN_CAVE_PASSAGEWAYS = 0x2F
    HECKRAN_CAVE_ENTRANCE = 0x30
    HECKRAN_CAVE_UNDERGROUND_RIVER = 0x31
    PORRE_MAYOR_1F = 0x32
    PORRE_MAYOR_2F = 0x33
    PORRE_RESIDENCE_1000 = 0x34
    SNAIL_STOP = 0x35
    PORRE_MARKET_1000 = 0x36
    PORRE_INN = 0x37
    PORRE_TICKET_OFFICE = 0x38
    FIONAS_SHRINE = 0x39
    CHORAS_MAYOR_1F = 0x3A
    CHORAS_MAYOR_2F = 0x3B
    ELH_MAGUS_HALL_AGGRESSION = 0x3C
    CHORAS_CARPENTER_1000 = 0x3D
    CHORAS_INN_1000 = 0x3E
    WEST_CAPE = 0x3F
    SUN_KEEP_1000 = 0x40
    NORTHERN_RUINS_ENTRANCE = 0x41
    NORTHERN_RUINS_BASEMENT = 0x42
    NORTHERN_RUINS_LANDING = 0x43
    NORTHERN_RUINS_ANTECHAMBER = 0x44
    NORTHERN_RUINS_VESTIBULE = 0x45
    NORTHERN_RUINS_BACK_ROOM = 0x46
    PRISON_CELLS = 0x47  # Guardia Jail
    PRISON_STAIRWELLS = 0x48
    NORTHERN_RUINS_HEROS_GRAVE = 0x49
    UNKNOWN_4A = 0x4A  # Unused
    PRISON_EXTERIOR = 0x4B
    UNKNOWN_4C = 0x4C
    UNKNOWN_4D = 0x4D
    UNKNOWN_4E = 0x4E
    EMP_GUARDIA_THRONEROOM = 0x4F
    EMP_MILLENNIAL_FAIR = 0x50
    EMP_LEENE_SQUARE = 0x51
    ENDING_SELECTOR_052 = 0x52
    FIONA_FOREST = 0x53
    EMP_END_OF_TIME = 0x54
    EMP_TELEPOD_EXHIBIT = 0x55
    EMP_DEATH_PEAK = 0x56
    ESG_MANORIA_SANCTUARY = 0x57
    THE_END = 0x58
    EMP_ZENAN_BRIDGE = 0x59
    EMP_PRISON_CATWALKS = 0x5A
    EPOTT_1 = 0x5B  # Ending: People of the Times
    EPOTT_2 = 0x5C
    EPOTT_3 = 0x5D
    EPOTT_4 = 0x5E
    EPOTT_5 = 0x5F
    BLACK_OMEN_ELDER_SPAWN = 0x60
    BLACK_OMEN_LOWER_TELEPORTERS = 0x61
    BLACK_OMEN_UPPER_TELEPORTERS = 0x62
    BLACK_OMEN_PLATFORM = 0x63
    BLACK_OMEN_ELEVATOR_DOWN = 0x64
    BLACK_OMEN_ELEVATOR_UP = 0x65
    JUNK_66 = 0x66
    JUNK_67 = 0x67
    JUNK_68 = 0x68
    JUNK_69 = 0x69
    JUNK_6A = 0x6A
    BLACK_OMEN_CELESTIAL_GATE = 0x6B
    LUCCA_EXPLAINS_PARADOXES = 0x6C
    ANCIENT_TYRANO_LAIR = 0x6D
    ANCIENT_TYRANO_LAIR_TRAPS = 0x6E
    ANCIENT_TYRANO_LAIR_NIZBELS_ROOM = 0x6F
    TRUCE_CANYON = 0x70
    TRUCE_CANYON_PORTAL = 0x71
    TRUCE_COUPLE_RESIDENCE_600 = 0x72
    TRUCE_SMITHY_RESIDENCE_600 = 0x73
    TRUCE_INN_600_1F = 0x74
    TRUCE_INN_600_2F = 0x75
    TRUCE_MARKET_600 = 0x76
    GUARDIA_FOREST_600 = 0x77
    GUARDIA_THRONEROOM_600 = 0x78
    KINGS_CHAMBER_600 = 0x79
    QUEENS_ROOM_600 = 0x7A
    GUARDIA_KITCHEN_600 = 0x7B
    GUARDIA_BARRACKS_600 = 0x7C
    MAGUS_CASTLE_DOPPLEGANGER_CORRIDOR = 0x7D
    GENO_DOME_CONVEYOR = 0x7E
    GENO_DOME_ELEVATOR = 0x7F
    GENO_DOME_LONG_CORRIDOR = 0x80  # where the power tab is on 2f
    MANORIA_SANCTUARY = 0x81
    MANORIA_MAIN_HALL = 0x82
    MANORIA_HEADQUARTERS = 0x83
    MANORIA_ROYAL_GUARD_HALL = 0x84
    ZENAN_BRIDGE_WRECKED = 0x85
    JUNK_86_ZENAN_BRIDGE_600 = 0x86
    ZENAN_BRIDGE_600 = 0x87
    DORINO_PERVERT_RESIDENCE = 0x88
    DORINO_ELDER_HOUSE = 0x89
    DORINO_INN = 0x8A
    DORINO_MARKET = 0x8B
    CURSED_WOODS = 0x8C
    FROGS_BURROW = 0x8D
    DENADORO_SOUTH_FACE = 0x8E
    DENADORO_CAVE_OF_MASAMUNE_EXTERIOR = 0x8F
    DENADORO_NORTH_FACE = 0x90
    DENADORO_ENTRANCE = 0x91
    DENADORO_LOWER_EAST_FACE = 0x92
    DENADORO_UPPER_EAST_FACE = 0x93
    DENADORO_MTN_VISTA = 0x94
    DENADORO_WEST_FACE = 0x95
    DENADORO_GAUNTLET = 0x96
    DENADORO_CAVE_OF_MASAMUNE = 0x97
    TATAS_HOUSE_1F = 0x98
    TATAS_HOUSE_2F = 0x99
    PORRE_ELDER = 0x9A
    PORRE_CAFE_600 = 0x9B
    PORRE_INN_600 = 0x9C
    PORRE_MARKET_600 = 0x9D
    FIONAS_VILLA = 0x9E
    SUNKEN_DESERT_ENTRANCE = 0x9F
    SUNKEN_DESERT_PARASITES = 0xA0
    SUNKEN_DESERT_DEVOURER = 0xA1
    JUNK_A2_OZZIES_FORT_ENTRANCE = 0xA2
    MAGIC_CAVE_EXTERIOR = 0xA3
    MAGIC_CAVE_INTERIOR = 0xA4
    MAGUS_CASTLE_EXTERIOR = 0xA5
    MAGUS_CASTLE_ENTRANCE = 0xA6
    MAGUS_CASTLE_GUILLOTINES = 0xA7
    MAGUS_CASTLE_PITS = 0xA8
    MAGUS_CASTLE_SLASH = 0xA9  # THRONE_OF_STRENGTH
    MAGUS_CASTLE_HALL_AGGRESSION = 0xAA
    MAGUS_CASTLE_HALL_DECEIT = 0xAB
    MAGUS_CASTLE_INNER_SANCTUM = 0xAC
    MAGUS_CASTLE_FLEA = 0xAD
    MAGUS_CASTLE_OZZIE = 0xAE
    MAGUS_CASTLE_HALL_APPREHENSION = 0xAF
    MAGUS_CASTLE_LOWER_BATTLEMENTS = 0xB0
    OZZIES_FORT_ENTRANCE = 0xB1
    OZZIES_FORT_HALL_DISREGARD = 0xB2  # Crank/pit room
    OZZIES_FORT_GUILLOTINE = 0xB3
    OZZIES_FORT_LAST_STAND = 0xB4
    OZZIES_FORT_THRONE_INCOMPETENCE = 0xB5
    JUNK_B6_OZZIES_FORT_FLEA_PLUS = 0xB6
    OZZIES_FORT_FLEA_PLUS = 0xB7
    OZZIES_FORT_SUPER_SLASH = 0xB8
    CHORAS_600_OLD_COUPLE_RESIDENCE = 0xB9
    CHORAS_600_CARPENTER_RESIDENCE_1F = 0xBA
    CHORAS_600_CARPENTER_RESIDENCE_2F = 0xBB
    CHORAS_CAFE = 0xBC
    CHORAS_600_INN = 0xBD
    CHORAS_600_MARKET = 0xBE
    SUN_KEEP_600 = 0xBF
    HECKRAN_CAVE_BOSS = 0xC0
    KINGS_TRIAL_NEW = 0xC1
    ZENAN_BRIDGE_BOSS = 0xC2
    GIANTS_CLAW_ENTRANCE = 0xC3
    GIANTS_CLAW_CAVERNS = 0xC4
    GIANTS_CLAW_TYRANO = 0xC5
    MANORIA_COMMAND = 0xC6
    MANORIA_CONFINEMENT = 0xC7
    MANORIA_SHRINE_ANTECHAMBER = 0xC8
    MANORIA_STORAGE = 0xC9
    MANORIA_KITCHEN = 0xCA
    MANORIA_SHRINE = 0xCB
    GUARDIA_FOREST_FROG_KING = 0xCC
    DENADORO_CYRUS_DIES = 0xCD
    GUARDIA_THRONEROOM_CYRUS = 0xCE
    JUNK_CF_SCHALAS_ROOM = 0xCF
    BANGOR_DOME = 0xD0
    BANGOR_DOME_SEALED_ROOM = 0xD1
    TRANN_DOME = 0xD2
    TRANN_DOME_SEALED_ROOM = 0xD3
    LAB_16_WEST = 0xD4
    LAB_16_EAST = 0xD5
    ARRIS_DOME = 0xD6
    ARRIS_DOME_INFESTATION = 0xD7
    ARRIS_DOME_AUXILIARY_CONSOLE = 0xD8  # First L+R password
    ARRIS_DOME_LOWER_COMMONS = 0xD9
    ARRIS_DOME_COMMAND = 0xDA
    ARRIS_DOME_GUARDIAN_CHAMBER = 0xDB
    ARRIS_DOME_SEALED_ROOM = 0xDC
    ARRIS_DOME_RAFTERS = 0xDD
    REPTITE_LAIR_2F = 0xDE
    LAB_32_WEST = 0xDF
    LAB_32 = 0xE0
    LAB_32_EAST = 0xE1
    PROTO_DOME = 0xE2
    PROTO_DOME_PORTAL = 0xE3
    FACTORY_RUINS_ENTRANCE = 0xE4
    FACTORY_RUINS_AUXILIARY_CONSOLE = 0xE5
    FACTORY_RUINS_SECURITY_CENTER = 0xE6
    FACTORY_RUINS_CRANE_ROOM = 0xE7
    FACTORY_RUINS_INFESTATION = 0xE8
    FACTORY_RUINS_CRANE_CONTROL = 0xE9
    FACTORY_RUINS_INFO_ARCHIVE = 0xEA
    FACTORY_RUINS_POWER_CORE = 0xEB
    SEWERS_B1 = 0xEC
    SEWERS_B2 = 0xED
    JUNK_EE_ETDP_PREHISTORIC_HUT = 0xEE
    ESS = 0xEF
    EGN = 0xF0
    KEEPERS_DOME = 0xF1
    KEEPERS_DOME_CORRIDOR = 0xF2
    KEEPERS_DOME_HANGAR = 0xF3
    DEATH_PEAK_ENTRANCE = 0xF4
    DEATH_PEAK_SOUTH_FACE = 0xF5
    DEATH_PEAK_SOUTHEAST_FACE = 0xF6
    DEATH_PEAK_NORTHEAST_FACE = 0xF7
    GENO_DOME_ENTRANCE = 0xF8
    GENO_DOME_CONVEYOR_ENTRANCE = 0xF9
    GENO_DOME_CONVEYOR_EXIT = 0xFA
    SUN_PALACE = 0xFB
    EDA_MILLENNIAL_FAIR = 0xFC
    SUN_KEEP_LAST_VILLAGE = 0xFD
    SKILL_TUTORIAL = 0xFE
    SUN_KEEP_2300 = 0xFF
    GENO_DOME_LABS = 0x100
    GENO_DOME_STORAGE = 0x101
    GENO_DOME_ROBOT_HUB = 0x102
    FACTORY_RUINS_DATA_CORE = 0x103
    DEATH_PEAK_NORTHWEST_FACE = 0x104
    PREHISTORIC_CANYON = 0x105
    DEATH_PEAK_UPPER_NORTH_FACE = 0x106
    DEATH_PEAK_LOWER_NORTH_FACE = 0x107
    DEATH_PEAK_CAVE = 0x108
    DEATH_PEAK_SUMMIT = 0x109
    JUNK_10A = 0x10A
    GENO_DOME_ROBOT_ELEVATOR_ACCESS = 0x10B
    GENO_DOME_MAINFRAME = 0x10C
    GENO_DOME_WASTE_DISPOSAL = 0x10D
    EDA_LEENE_SQUARE = 0x10E
    SPECIAL_PURPOSE_AREA = 0x10F
    MYSTIC_MTN_PORTAL = 0x110
    MYSTIC_MTN_BASE = 0x111
    MYSTIC_MTN_GULCH = 0x112
    IOKA_CHIEFS_HUT = 0x113
    IOKA_SOUTHWEST_HUT = 0x114
    IOKA_TRADING_POST = 0x115
    IOKA_SWEETWATER_HUT = 0x116
    IOKA_MEETING_SITE = 0x117
    IOKA_MEETING_SITE_PARTY = 0x118
    FOREST_MAZE_ENTRANCE = 0x119
    FOREST_MAZE = 0x11A
    REPTITE_LAIR_ENTRANCE = 0x11B
    REPTITE_LAIR_1F = 0x11C
    REPTITE_LAIR_WEEVIL_BURROWS_B1 = 0x11D
    REPTITE_LAIR_WEEVIL_BURROWS_B2 = 0x11E
    REPTITE_LAIR_COMMONS = 0x11F
    REPTITE_LAIR_TUNNEL = 0x120
    REPTITE_LAIR_AZALA_ROOM = 0x121
    REPTITE_LAIR_ACCESS_SHAFT = 0x122
    HUNTING_RANGE = 0x123
    LARUBA_RUINS = 0x124
    DACTYL_NEST_LOWER = 0x125
    DACTYL_NEST_UPPER = 0x126
    DACTYL_NEST_SUMMIT = 0x127
    GIANTS_CLAW_LAIR_ENTRANCE = 0x128
    GIANTS_CLAW_LAIR_THRONEROOM = 0x129
    TYRANO_LAIR_EXTERIOR = 0x12A
    TYRANO_LAIR_ENTRANCE = 0x12B
    TYRANO_LAIR_THRONEROOM = 0x12C
    TYRANO_LAIR_KEEP = 0x12D
    TYRANO_LAIR_ANTECHAMBERS = 0x12E
    TYRANO_LAIR_STORAGE = 0x12F
    TYRANO_LAIR_NIZBEL = 0x130
    TYRANO_LAIR_ROOM_OF_VERTIGO = 0x131
    DEBUG_ROOM = 0x132
    LAIR_RUINS_PORTAL = 0x133
    BLACK_OMEN_1F_ENTRANCE = 0x134
    BLACK_OMEN_1F_WALKWAY = 0x135
    BLACK_OMEN_1F_DEFENSE_CORRIDOR = 0x136
    BLACK_OMEN_1F_STAIRWAY = 0x137
    BLACK_OMEN_3F_WALKWAY = 0x138
    BLACK_OMEN_47F_AUX_COMMAND = 0x139
    BLACK_OMEN_47F_GRAND_HALL = 0x13A
    BLACK_OMEN_47F_EMPORIUM = 0x13B
    BLACK_OMEN_47F_ROYAL_PATH = 0x13C
    BLACK_OMEN_47F_ROYAL_BALLROOM = 0x13D
    BLACK_OMEN_47F_ROYAL_ASSEMBLY = 0x13E
    BLACK_OMEN_47F_ROYAL_PROMENADE = 0x13F
    BLACK_OMEN_ROYAL_TELEPORTER_LOWER = 0x140
    BLACK_OMEN_ROYAL_TELEPORTER_UPPER = 0x141
    BLACK_OMEN_63F_DIVINE_ESPLENADE = 0x142
    BLACK_OMEN_GIGA_MUTANT = 0x143
    BLACK_OMEN_97F_ASTRAL_WALKWAY = 0x144
    BLACK_OMEN_TERRA_MUTANT = 0x145
    BLACK_OMEN_98F_ASTRAL_WALKWAY = 0x146
    SUN_KEEP_65MBC = 0x147
    ZEAL_PALACE_SCHALAS_ROOM = 0x148
    ZEAL_PALACE_REGAL_HALL = 0x149
    ZEAL_PALACE_CORRIDOR_TO_MAMMON = 0x14A
    ZEAL_PALACE_HALL_OF_MAMMON = 0x14B
    ZEAL_PALACE_THRONE = 0x14C
    ZEAL_PALACE_HALL_OF_MAMMON_NIGHT = 0x14D
    ZEAL_PALACE_THRONE_NIGHT = 0x14E
    JUNK_14F_ENHASA = 0x14F
    LAND_BRIDGE_ENHASA_N = 0x150
    SKYWAY_ENHASA_S = 0x151
    ETDP_PRESENT_AGE_HOME = 0x152
    ETDP_PREHISTORIC_AGE_JUNGLE = 0x153
    ETDP_DARK_AGE_OCEAN_PALACE = 0x154
    ETDP_PRESENT_AGE_JAIL = 0x155
    ETDP_DARK_AGE_EARTHBOUND = 0x156
    ETDP_PRESENT_AGE_NORTHERN_RUINS = 0x157
    ARRIS_DOME_FOOD_LOCKER = 0x158
    ETO_LUCCAS_WORKSHOP = 0x159
    GAUNTLET_ARRIS_DOME_GUARDIAN = 0x15A
    GAUNTLET_PRISON_CATWALKS = 0x15B
    GAUNTLET_HECKRAN_CAVE = 0x15C
    GAUNTLET_ZENAN_BRIDGE = 0x15D
    GAUNTLET_CAVE_OF_MASAMUNE = 0x15E
    DARK_AGES_PORTAL = 0x15F
    LAND_BRIDGE_KAJAR = 0x160
    LAND_BRIDGE_ENHASA_S = 0x161
    SKYWAY_ENHASA_N = 0x162
    ENHASA = 0x163
    SKYWAY_KAJAR = 0x164
    KAJAR = 0x165
    KAJAR_STUDY = 0x166
    KAJAR_ROCK_ROOM = 0x167
    KAJAR_MAGIC_LAB = 0x168
    ENHASA_NU_ROOM = 0x169
    BLACKBIRD_SCAFFOLDING = 0x16A
    BLACKBIRD_LEFT_WING = 0x16B
    BLACKBIRD_RIGHT_PORT = 0x16C
    BLACKBIRD_LEFT_PORT = 0x16D
    BLACKBIRD_OVERHEAD = 0x16E
    BLACKBIRD_HANGAR = 0x16F
    BLACKBIRD_REAR_HALLS = 0x170
    BLACKBIRD_FORWARD_HALLS = 0x171
    BLACKBIRD_TREASURY = 0x172
    BLACKBIRD_CELL = 0x173
    BLACKBIRD_BARRACKS = 0x174
    BLACKBIRD_ARMORY_3 = 0x175
    BLACKBIRD_INVENTORY = 0x176
    BLACKBIRD_LOUNGE = 0x177
    BLACKBIRD_DUCTS = 0x178
    REBORN_EPOCH = 0x179
    ETDP_FUTURE_AGE_ROOM = 0x17A
    ETPD_END_OF_TIME = 0x17B
    ALGETTY = 0x17C
    ALGETTY_INN = 0x17D
    ALGETTY_ELDERS_GROTTO = 0x17E
    ALGETTY_COMMONERS_GROTTO = 0x17F
    ALGETTY_SHOP = 0x180
    JUNK_181_ALGETTY_TSUNAMI = 0x181
    ALGETTY_ENTRANCE = 0x182
    JUNK_183_BEAST_NEST = 0x183
    BEAST_NEST = 0x184
    ZEAL_TELEPORTERS = 0x185
    ETDP_PREHISTORIC_HUT = 0x186
    ETDP_MAGUS_ROOM = 0x187
    MT_WOE_WESTERN_FACE = 0x188
    MT_WOE_LOWER_EASTERN_FACE = 0x189
    MT_WOE_MIDDLE_EASTERN_FACE = 0x18A
    MT_WOE_UPPER_EASTERN_FACE = 0x18B
    JUNK_18C_MT_WOE_SUMMIT = 0x18C
    MT_WOE_SUMMIT = 0x18D
    EWTPS_LEENE_SQUARE = 0x18E
    EWTPS_CRONOS_KITCHEN = 0x18F
    THE_END_190 = 0x190
    ZEAL_PALACE = 0x191
    ZEAL_PALACE_HALLWAY = 0x192
    ZEAL_PALACE_STUDY = 0x193
    OCEAN_PALACE_ENTRANCE = 0x194
    OCEAN_PALACE_PIAZZA = 0x195
    OCEAN_PALACE_SIDE_ROOMS = 0x196
    OCEAN_PALACE_FORWARD_AREA = 0x197
    OCEAN_PALACE_B3_LANDING = 0x198
    OCEAN_PALACE_GRAND_STAIRWELL = 0x199
    OCEAN_PALACE_B20_LANDING = 0x19A
    OCEAN_PALACE_SOUTHERN_ACCESS_LIFT = 0x19B
    OCEAN_PALACE_SECURITY_POOL = 0x19C
    OCEAN_PALACE_SECURITY_ESPLANADE = 0x19D
    OCEAN_PALACE_REGAL_ANTECHAMBER = 0x19E
    OCEAN_PALACE_THRONE = 0x19F
    OCEAN_PALACE_UNK_1A0 = 0x1A0
    OCEAN_PALACE_EASTERN_ACCESS_LIFT = 0x1A1
    OCEAN_PALACE_WESTERN_ACCESS_LIFT = 0x1A2
    JUNK_1A3_TIME_FREEZE = 0x1A3
    JUNK_1A4_TIME_FREEZE = 0x1A4
    JUNK_1A5_TIME_FREEZE = 0x1A5
    TIME_DISTORTION_PROFANE_MACHINE = 0x1A6
    OCEAN_PALACE_TIME_FREEZE = 0x1A7
    LAST_VILLAGE_COMMONS = 0x1A8
    LAST_VILLAGE_EMPTY_HUT = 0x1A9
    LAST_VILLAGE_SHOP = 0x1AA
    LAST_VILLAGE_RESIDENCE = 0x1AB
    NORTH_CAPE = 0x1AC
    DEATH_PEAK_SUMMIT_AFTER = 0x1AD
    TYRANO_LAIR_MAIN_CELL = 0x1AE
    JUNK_1AF_TITLE_SCREEN = 0x1AF
    FLYING_EPOCH = 0x1B0
    TITLE_SCREEN = 0x1B1
    BEKKLERS_LAB = 0x1B2
    MAGIC_CAVE_EXTERIOR_OPEN = 0x1B3
    FIONA_FOREST_CAMPFIRE = 0x1B4
    FACTORY_RUINS_ROBOT_STORAGE = 0x1B5
    KINGS_TRIAL = 0x1B6
    LEENE_SQUARE = 0x1B7
    GUARDIA_REAR_STORAGE = 0x1B8
    COURTROOM_LOBBY = 0x1B9
    BLACKBIRD_ACCESS_SHAFT = 0x1BA
    BLACKBIRD_ARMORY_2 = 0x1BB
    BLACKBIRD_ARMORY_1 = 0x1BC
    BLACKBIRD_STORAGE = 0x1BD
    MAGUS_CASTLE_UPPER_BATTLEMENTS = 0x1BE
    MAGUS_CASTLE_GRAND_STAIRWAY = 0x1BF
    JUNK_1C0 = 0x1C0
    BLACK_OMEN_ENTRANCE = 0x1C1
    BLACK_OMEN_98F_OMEGA_DEFENSE = 0x1C2
    BLACK_OMEN_ZEAL = 0x1C3
    JUNK_1C4 = 0x1C4
    JUNK_1C5 = 0x1C5
    JUNK_1C6 = 0x1C6
    JUNK_1C7 = 0x1C7
    GAUNTLET_REPTITE_LAIR = 0x1C8
    GAUTNLET_MAGUS_INNER_SANCTUM = 0x1C9
    GAUNTLET_TYRANO_LAIR = 0x1CA
    GAUNTLET_MT_WOE_SUMMIT = 0x1CB
    ETO_CREDITS = 0x1CC
    EMPTY_1CD = 0x1CD
    EMPTY_1CE = 0x1CE
    EMPTY_1CF = 0x1CF
    END_OF_TIME = 0x1D0
    SPEKKIO = 0x1D1
    APOLCALYPSE_LAVOS = 0x1D2
    LAVOS = 0x1D3
    GUARDIA_QUEENS_TOWER_600 = 0x1D4
    MAGUS_CASTLE_CORRIDOR_OF_COMBAT = 0x1D5
    MAGUS_CASTLE_HALL_OF_AMBUSH = 0x1D6
    MAGUS_CASTLE_DUNGEON = 0x1D7
    APOCALYPSE_EPOCH = 0x1D8
    END_OF_TIME_EPOCH = 0x1D9
    LAVOS_TUNNEL = 0x1DA
    LAVOS_CORE = 0x1DB
    TRUCE_DOME = 0x1DC
    EMERGENCE_OF_BLACK_OMEN = 0x1DD
    BLACKBIRD_WING_ACCESS = 0x1DE
    TESSERACT = 0x1DF
    GUARDIA_KINGS_TOWER_600 = 0x1E0
    DEATH_OF_BLACKBIRD = 0x1E1
    JUNK_1E2_BLACKBIRD = 0x1E2
    JUNK_1E3_BLACKBIRD = 0x1E3
    JUNK_1E4_BLACKBIRD = 0x1E4
    JUNK_1E5_BLACKBIRD = 0x1E5
    GUARDIA_KINGS_TOWER_1000 = 0x1E6
    GUARDIA_QUEENS_TOWER_1000 = 0x1E7
    GUARDIA_LAWGIVERS_TOWER = 0x1E8
    GUARDIA_PRISON_TOWER = 0x1E9
    ANCIENT_TYRANO_LAIR_VERTIGO = 0x1EA
    EMPTY_1EB = 0x1EB
    EMPTY_1EC = 0x1EC
    ALGETTY_TSUNAMI = 0x1ED
    PARADISE_LOST = 0x1EE
    DEATH_PEAK_GUARDIAN_SPAWN = 0x1EF
    OW_PRESENT = 0x1F0
    OW_MIDDLE_AGES = 0x1F1
    OW_FUTURE = 0x1F2
    OW_PREHISTORIC = 0x1F3
    OW_DARK_AGES = 0x1F4
    OW_ZEAL = 0x1F5
    OW_LAST_VILLAGE = 0x1F6
    OW_APOCALYPSE = 0x1F7
    EMPTY_1F8 = 0x1F8
    EMPTY_1F9 = 0x1F9
    EMPTY_1FA = 0x1FA
    EMPTY_1FB = 0x1FB
    EMPTY_1FC = 0x1FC
    EMPTY_1FD = 0x1FD
    EMPTY_1FE = 0x1FE
    EMPTY_1FF = 0x1FF


# Copied and reformatted from Anguirel's list
class ItemID(StrIntEnum):
    """Item ID enumeration"""

    NONE = 0x00
    WOOD_SWORD = 0x01
    IRON_BLADE = 0x02
    STEELSABER = 0x03
    LODE_SWORD = 0x04
    RED_KATANA = 0x05
    FLINT_EDGE = 0x06
    DARK_SABER = 0x07
    AEON_BLADE = 0x08
    DEMON_EDGE = 0x09
    ALLOYBLADE = 0x0A
    STAR_SWORD = 0x0B
    VEDICBLADE = 0x0C
    KALI_BLADE = 0x0D
    SHIVA_EDGE = 0x0E
    BOLT_SWORD = 0x0F
    SLASHER = 0x10
    BRONZE_BOW = 0x11
    IRON_BOW = 0x12
    LODE_BOW = 0x13
    ROBIN_BOW = 0x14
    SAGE_BOW = 0x15
    DREAM_BOW = 0x16
    COMETARROW = 0x17
    SONICARROW = 0x18
    VALKERYE = 0x19
    SIREN = 0x1A
    SCALING_LEVEL = 0x1B
    OBJECTIVE_1 = 0x1C
    OBJECTIVE_2 = 0x1D
    OBJECTIVE_3 = 0x1E
    AIR_GUN = 0x1F
    DART_GUN = 0x20
    AUTO_GUN = 0x21
    PICOMAGNUM = 0x22
    PLASMA_GUN = 0x23
    RUBY_GUN = 0x24
    DREAM_GUN = 0x25
    MEGABLAST = 0x26
    SHOCK_WAVE = 0x27
    WONDERSHOT = 0x28
    GRAEDUS = 0x29
    OBJECTIVE_4 = 0x2A
    OBJECTIVE_5 = 0x2B
    OBJECTIVE_6 = 0x2C
    OBJECTIVE_7 = 0x2D
    TIN_ARM = 0x2E
    HAMMER_ARM = 0x2F
    MIRAGEHAND = 0x30
    STONE_ARM = 0x31
    DOOMFINGER = 0x32
    MAGMA_HAND = 0x33
    MEGATONARM = 0x34
    BIG_HAND = 0x35
    KAISER_ARM = 0x36
    GIGA_ARM = 0x37
    TERRA_ARM = 0x38
    CRISIS_ARM = 0x39
    OBJECTIVE_8 = 0x3A
    BRONZEEDGE = 0x3B
    IRON_SWORD = 0x3C
    MASAMUNE_1 = 0x3D
    FLASHBLADE = 0x3E
    PEARL_EDGE = 0x3F
    RUNE_BLADE = 0x40
    BRAVESWORD = 0x41
    MASAMUNE_2 = 0x42
    DEMON_HIT = 0x43
    FIST = 0x44
    FIST_2 = 0x45
    FIST_3 = 0x46
    IRON_FIST = 0x47
    BRONZEFIST = 0x48
    UNUSED_49 = 0x49
    UNUSED_4A = 0x4A
    DARKSCYTHE = 0x4B
    HURRICANE = 0x4C
    STARSCYTHE = 0x4D
    DOOMSICKLE = 0x4E
    MOP = 0x4F
    BENT_SWORD = 0x50
    BENT_HILT = 0x51
    MASAMUNE_0_ATK = 0x52
    SWALLOW = 0x53
    SLASHER_2 = 0x54
    RAINBOW = 0x55
    UNUSED_56 = 0x56
    UNUSED_57 = 0x57
    UNUSED_58 = 0x58
    UNUSED_59 = 0x59
    WEAPON_END_5A = 0x5A
    HIDE_TUNIC = 0x5B
    KARATE_GI = 0x5C
    BRONZEMAIL = 0x5D
    MAIDENSUIT = 0x5E
    IRON_SUIT = 0x5F
    TITAN_VEST = 0x60
    GOLD_SUIT = 0x61
    RUBY_VEST = 0x62
    DARK_MAIL = 0x63
    MIST_ROBE = 0x64
    MESO_MAIL = 0x65
    LUMIN_ROBE = 0x66
    FLASH_MAIL = 0x67
    LODE_VEST = 0x68
    AEON_SUIT = 0x69
    ZODIACCAPE = 0x6A
    NOVA_ARMOR = 0x6B
    PRISMDRESS = 0x6C
    MOON_ARMOR = 0x6D
    RUBY_ARMOR = 0x6E
    RAVENARMOR = 0x6F
    GLOOM_CAPE = 0x70
    WHITE_MAIL = 0x71
    BLACK_MAIL = 0x72
    BLUE_MAIL = 0x73
    RED_MAIL = 0x74
    WHITE_VEST = 0x75
    BLACK_VEST = 0x76
    BLUE_VEST = 0x77
    RED_VEST = 0x78
    TABAN_VEST = 0x79
    TABAN_SUIT = 0x7A
    ARMOR_END_7B = 0x7B
    HIDE_CAP = 0x7C
    BRONZEHELM = 0x7D
    IRON_HELM = 0x7E
    BERET = 0x7F
    GOLD_HELM = 0x80
    ROCK_HELM = 0x81
    CERATOPPER = 0x82
    GLOW_HELM = 0x83
    LODE_HELM = 0x84
    AEON_HELM = 0x85
    PRISM_HELM = 0x86
    DOOM_HELM = 0x87
    DARK_HELM = 0x88
    GLOOM_HELM = 0x89
    SAFE_HELM = 0x8A
    TABAN_HELM = 0x8B
    SIGHT_CAP = 0x8C
    MEMORY_CAP = 0x8D
    TIME_HAT = 0x8E
    VIGIL_HAT = 0x8F
    OZZIEPANTS = 0x90
    HASTE_HELM = 0x91
    RBOW_HELM = 0x92
    MERMAIDCAP = 0x93
    HELM_END_94 = 0x94
    BANDANA = 0x95
    RIBBON = 0x96
    POWERGLOVE = 0x97
    DEFENDER = 0x98
    MAGICSCARF = 0x99
    AMULET = 0x9A
    DASH_RING = 0x9B
    HIT_RING = 0x9C
    POWER_RING = 0x9D
    MAGIC_RING = 0x9E
    WALL_RING = 0x9F
    SILVERERNG = 0xA0
    GOLD_ERNG = 0xA1
    SILVERSTUD = 0xA2
    GOLD_STUD = 0xA3
    SIGHTSCOPE = 0xA4
    CHARM_TOP = 0xA5
    RAGE_BAND = 0xA6
    FRENZYBAND = 0xA7
    THIRD_EYE = 0xA8
    WALLET = 0xA9
    GREENDREAM = 0xAA
    BERSERKER = 0xAB
    POWERSCARF = 0xAC
    SPEED_BELT = 0xAD
    BLACK_ROCK = 0xAE
    BLUE_ROCK = 0xAF
    SILVERROCK = 0xB0
    WHITE_ROCK = 0xB1
    GOLD_ROCK = 0xB2
    HERO_MEDAL = 0xB3
    MUSCLERING = 0xB4
    FLEA_VEST = 0xB5
    MAGIC_SEAL = 0xB6
    POWER_SEAL = 0xB7
    RELIC_UNUSED = 0xB8
    VALOR_CREST = 0xB8
    SERAPHSONG = 0xB9
    DRAGON_TEAR = 0xB9
    SUN_SHADES = 0xBA
    PRISMSPECS = 0xBB
    ACCESSORY_END_BC = 0xBC
    TONIC = 0xBD
    MID_TONIC = 0xBE
    FULL_TONIC = 0xBF
    ETHER = 0xC0
    MID_ETHER = 0xC1
    FULL_ETHER = 0xC2
    ELIXIR = 0xC3
    HYPERETHER = 0xC4
    MEGAELIXIR = 0xC5
    HEAL = 0xC6
    REVIVE = 0xC7
    SHELTER = 0xC8
    POWER_MEAL = 0xC9
    LAPIS = 0xCA
    BARRIER = 0xCB
    SHIELD = 0xCC
    POWER_TAB = 0xCD
    MAGIC_TAB = 0xCE
    SPEED_TAB = 0xCF
    PETAL = 0xD0
    FANG = 0xD1
    HORN = 0xD2
    FEATHER = 0xD3
    SEED = 0xD4
    BIKE_KEY = 0xD5
    PENDANT = 0xD6
    GATE_KEY = 0xD7
    PRISMSHARD = 0xD8
    C_TRIGGER = 0xD9
    TOOLS = 0xDA
    JERKY = 0xDB
    DREAMSTONE = 0xDC
    RACE_LOG = 0xDD
    MOON_STONE = 0xDE
    SUN_STONE = 0xDF
    RUBY_KNIFE = 0xE0
    YAKRA_KEY = 0xE1
    CLONE = 0xE2
    TOMAS_POP = 0xE3
    PETALS_2 = 0xE4
    FANGS_2 = 0xE5
    HORNS_2 = 0xE6
    FEATHERS_2 = 0xE7
    BUCKETFRAG = 0xE8
    JETSOFTIME = 0xE9
    PENDANT_CHARGE = 0xEA
    RAINBOW_SHELL = 0xEB
    UNUSED_EC = 0xEC
    UNUSED_ED = 0xED
    UNUSED_EE = 0xEE
    UNUSED_EF = 0xEF
    UNUSED_F0 = 0xF0
    UNUSED_F1 = 0xF1


# Extracted from Anguirel's Chronosanity code
# Non-Chronosanity chests checked vs frankin's (?) spreadsheet at
# https://docs.google.com/spreadsheets/
#   d/19-CgUeYJrHJ8A1jJJWN1gvGaiFyvM5_aoE15POjW8YQ/edit#gid=1968430651
class TreasureID(StrIntEnum):
    """Enumeration of all treasures."""

    MT_WOE_1ST_SCREEN = auto()
    MT_WOE_2ND_SCREEN_1 = auto()
    MT_WOE_2ND_SCREEN_2 = auto()
    MT_WOE_2ND_SCREEN_3 = auto()
    MT_WOE_2ND_SCREEN_4 = auto()
    MT_WOE_2ND_SCREEN_5 = auto()
    MT_WOE_3RD_SCREEN_1 = auto()
    MT_WOE_3RD_SCREEN_2 = auto()
    MT_WOE_3RD_SCREEN_3 = auto()
    MT_WOE_3RD_SCREEN_4 = auto()
    MT_WOE_3RD_SCREEN_5 = auto()
    MT_WOE_FINAL_1 = auto()
    MT_WOE_FINAL_2 = auto()
    MT_WOE_KEY = auto()
    FIONA_KEY = auto()
    ARRIS_DOME_RATS = auto()
    ARRIS_DOME_FOOD_STORE = auto()
    ARRIS_DOME_DOAN_KEY = auto()
    ARRIS_DOME_FOOD_LOCKER_KEY = auto()
    SUN_PALACE_KEY = auto()
    SEWERS_1 = auto()
    SEWERS_2 = auto()
    SEWERS_3 = auto()
    LAB_16_1 = auto()
    LAB_16_2 = auto()
    LAB_16_3 = auto()
    LAB_16_4 = auto()
    LAB_32_1 = auto()
    PRISON_TOWER_1000 = auto()
    GENO_DOME_1F_1 = auto()
    GENO_DOME_1F_2 = auto()
    GENO_DOME_1F_3 = auto()
    GENO_DOME_1F_4 = auto()
    GENO_DOME_ROOM_1 = auto()
    GENO_DOME_ROOM_2 = auto()
    GENO_DOME_PROTO4_1 = auto()
    GENO_DOME_PROTO4_2 = auto()
    GENO_DOME_2F_1 = auto()
    GENO_DOME_2F_2 = auto()
    GENO_DOME_2F_3 = auto()
    GENO_DOME_2F_4 = auto()
    GENO_DOME_BOSS_1 = auto()
    GENO_DOME_BOSS_2 = auto()
    FACTORY_LEFT_AUX_CONSOLE = auto()
    FACTORY_LEFT_SECURITY_RIGHT = auto()
    FACTORY_LEFT_SECURITY_LEFT = auto()
    FACTORY_RIGHT_DATA_CORE_1 = auto()
    FACTORY_RIGHT_DATA_CORE_2 = auto()
    FACTORY_RIGHT_FLOOR_TOP = auto()
    FACTORY_RIGHT_FLOOR_LEFT = auto()
    FACTORY_RIGHT_FLOOR_BOTTOM = auto()
    FACTORY_RIGHT_FLOOR_SECRET = auto()
    FACTORY_RIGHT_CRANE_LOWER = auto()
    FACTORY_RIGHT_CRANE_UPPER = auto()
    FACTORY_RIGHT_INFO_ARCHIVE = auto()
    # Inaccessible Robot storage chest omitted -- would be 0xE7
    # GIANTS_CLAW_KINO_CELL = auto()
    GIANTS_CLAW_TRAPS = auto()
    GIANTS_CLAW_CAVES_1 = auto()
    GIANTS_CLAW_CAVES_2 = auto()
    GIANTS_CLAW_CAVES_3 = auto()
    GIANTS_CLAW_CAVES_4 = auto()
    GIANTS_CLAW_CAVES_5 = auto()
    GIANTS_CLAW_ROCK = auto()
    GIANTS_CLAW_KEY = auto()
    # Weirdness with Northern Ruins.  There's a variable set, only for these
    # locations indicating whether you're in the 600 or 1000 version
    #   0x7F10A3 & 0x10 ->  600
    #   0x7F10A3 & 0x20 -> 1000
    # On 0x44 Northern Ruins Antechamber
    NORTHERN_RUINS_ANTECHAMBER_LEFT_600 = auto()
    NORTHERN_RUINS_ANTECHAMBER_SEALED_600 = auto()
    NORTHERN_RUINS_ANTECHAMBER_LEFT_1000 = auto()
    NORTHERN_RUINS_ANTECHAMBER_SEALED_1000 = auto()
    # On 0x46 Northern Ruins Back Room
    NORTHERN_RUINS_BACK_LEFT_SEALED_600 = auto()
    NORTHERN_RUINS_BACK_RIGHT_SEALED_600 = auto()
    NORTHERN_RUINS_BACK_LEFT_SEALED_1000 = auto()
    NORTHERN_RUINS_BACK_RIGHT_SEALED_1000 = auto()
    # On 0x42 Northern Ruins Basement Corridor
    NORTHERN_RUINS_BASEMENT_600 = auto()
    # Frog locked one
    NORTHERN_RUINS_BASEMENT_1000 = auto()
    GUARDIA_BASEMENT_1 = auto()
    GUARDIA_BASEMENT_2 = auto()
    GUARDIA_BASEMENT_3 = auto()
    GUARDIA_TREASURY_1 = auto()
    GUARDIA_TREASURY_2 = auto()
    GUARDIA_TREASURY_3 = auto()
    KINGS_TRIAL_KEY = auto()
    OZZIES_FORT_GUILLOTINES_1 = auto()
    OZZIES_FORT_GUILLOTINES_2 = auto()
    OZZIES_FORT_GUILLOTINES_3 = auto()
    OZZIES_FORT_GUILLOTINES_4 = auto()
    OZZIES_FORT_FINAL_1 = auto()
    OZZIES_FORT_FINAL_2 = auto()
    # OZZIES_FORT_KEY = auto()
    TRUCE_MAYOR_1F = auto()
    TRUCE_MAYOR_2F = auto()
    FOREST_RUINS = auto()
    PORRE_MAYOR_2F = auto()
    TRUCE_CANYON_1 = auto()
    TRUCE_CANYON_2 = auto()
    FIONAS_HOUSE_1 = auto()
    FIONAS_HOUSE_2 = auto()
    CURSED_WOODS_1 = auto()
    CURSED_WOODS_2 = auto()
    FROGS_BURROW_RIGHT = auto()
    ZENAN_BRIDGE_CHEF = auto()
    ZENAN_BRIDGE_CHEF_TAB = auto()
    ZENAN_BRIDGE_CAPTAIN = auto()
    SNAIL_STOP_KEY = auto()
    LAZY_CARPENTER = auto()
    HECKRAN_CAVE_SIDETRACK = auto()
    HECKRAN_CAVE_ENTRANCE = auto()
    HECKRAN_CAVE_1 = auto()
    HECKRAN_CAVE_2 = auto()
    # Taban items are weird, but the first one can be a normal ScriptTreasure
    # Maybe the rest can be too!
    TABAN_GIFT_VEST = auto()
    KINGS_ROOM_1000 = auto()
    QUEENS_ROOM_1000 = auto()
    KINGS_ROOM_600 = auto()
    QUEENS_ROOM_600 = auto()
    ROYAL_KITCHEN = auto()
    QUEENS_TOWER_600 = auto()
    KINGS_TOWER_600 = auto()
    KINGS_TOWER_1000 = auto()
    QUEENS_TOWER_1000 = auto()
    GUARDIA_COURT_TOWER = auto()
    MANORIA_CATHEDRAL_1 = auto()
    MANORIA_CATHEDRAL_2 = auto()
    MANORIA_CATHEDRAL_3 = auto()
    MANORIA_INTERIOR_1 = auto()
    MANORIA_INTERIOR_2 = auto()
    MANORIA_INTERIOR_3 = auto()
    MANORIA_INTERIOR_4 = auto()
    MANORIA_SHRINE_SIDEROOM_1 = auto()
    MANORIA_SHRINE_SIDEROOM_2 = auto()
    MANORIA_BROMIDE_1 = auto()
    MANORIA_BROMIDE_2 = auto()
    MANORIA_BROMIDE_3 = auto()
    MANORIA_SHRINE_MAGUS_1 = auto()
    MANORIA_SHRINE_MAGUS_2 = auto()
    YAKRAS_ROOM = auto()
    DENADORO_MTS_SCREEN2_1 = auto()
    DENADORO_MTS_SCREEN2_2 = auto()
    DENADORO_MTS_SCREEN2_3 = auto()
    DENADORO_MTS_FINAL_1 = auto()
    DENADORO_MTS_FINAL_2 = auto()
    DENADORO_MTS_FINAL_3 = auto()
    DENADORO_MTS_WATERFALL_TOP_1 = auto()
    DENADORO_MTS_WATERFALL_TOP_2 = auto()
    DENADORO_MTS_WATERFALL_TOP_3 = auto()
    DENADORO_MTS_WATERFALL_TOP_4 = auto()
    DENADORO_MTS_WATERFALL_TOP_5 = auto()
    DENADORO_MTS_ENTRANCE_1 = auto()
    DENADORO_MTS_ENTRANCE_2 = auto()
    DENADORO_MTS_SCREEN3_1 = auto()
    DENADORO_MTS_SCREEN3_2 = auto()
    DENADORO_MTS_SCREEN3_3 = auto()
    DENADORO_MTS_SCREEN3_4 = auto()
    DENADORO_MTS_AMBUSH = auto()
    DENADORO_MTS_SAVE_PT = auto()
    DENADORO_MTS_KEY = auto()
    BANGOR_DOME_SEAL_1 = auto()
    BANGOR_DOME_SEAL_2 = auto()
    BANGOR_DOME_SEAL_3 = auto()
    TRANN_DOME_SEAL_1 = auto()
    TRANN_DOME_SEAL_2 = auto()
    ARRIS_DOME_SEAL_1 = auto()
    ARRIS_DOME_SEAL_2 = auto()
    ARRIS_DOME_SEAL_3 = auto()
    ARRIS_DOME_SEAL_4 = auto()
    TRUCE_INN_SEALED_600 = auto()
    PORRE_ELDER_SEALED_1 = auto()
    PORRE_ELDER_SEALED_2 = auto()
    GUARDIA_CASTLE_SEALED_600 = auto()
    GUARDIA_FOREST_SEALED_600 = auto()
    TRUCE_INN_SEALED_1000 = auto()
    PORRE_MAYOR_SEALED_1 = auto()
    PORRE_MAYOR_SEALED_2 = auto()
    GUARDIA_FOREST_SEALED_1000 = auto()
    GUARDIA_CASTLE_SEALED_1000 = auto()
    HECKRAN_SEALED_1 = auto()
    HECKRAN_SEALED_2 = auto()
    PYRAMID_LEFT = auto()
    PYRAMID_RIGHT = auto()
    MAGIC_CAVE_SEALED = auto()
    MYSTIC_MT_STREAM = auto()
    FOREST_MAZE_1 = auto()
    FOREST_MAZE_2 = auto()
    FOREST_MAZE_3 = auto()
    FOREST_MAZE_4 = auto()
    FOREST_MAZE_5 = auto()
    FOREST_MAZE_6 = auto()
    FOREST_MAZE_7 = auto()
    FOREST_MAZE_8 = auto()
    FOREST_MAZE_9 = auto()
    REPTITE_LAIR_REPTITES_1 = auto()
    REPTITE_LAIR_REPTITES_2 = auto()
    REPTITE_LAIR_KEY = auto()
    DACTYL_NEST_1 = auto()
    DACTYL_NEST_2 = auto()
    DACTYL_NEST_3 = auto()
    MELCHIOR_RAINBOW_SHELL = auto()
    MELCHIOR_SUNSTONE_RAINBOW = auto()
    MELCHIOR_SUNSTONE_SPECS = auto()

    FROGS_BURROW_LEFT = auto()

    # Non-Chronosanity chests:
    GUARDIA_JAIL_FRITZ_STORAGE = auto()
    GUARDIA_JAIL_CELL = auto()
    GUARDIA_JAIL_OMNICRONE_1 = auto()
    GUARDIA_JAIL_OMNICRONE_2 = auto()
    GUARDIA_JAIL_OMNICRONE_3 = auto()
    GUARDIA_JAIL_HOLE_1 = auto()
    GUARDIA_JAIL_HOLE_2 = auto()
    GUARDIA_JAIL_OUTER_WALL = auto()
    GUARDIA_JAIL_OMNICRONE_4 = auto()
    GUARDIA_JAIL_FRITZ = auto()
    MAGUS_CASTLE_RIGHT_HALL = auto()
    SUNKEN_DESERT_B1_NW = auto()
    SUNKEN_DESERT_B1_NE = auto()
    SUNKEN_DESERT_B1_SE = auto()
    SUNKEN_DESERT_B1_SW = auto()
    SUNKEN_DESERT_B2_NW = auto()
    SUNKEN_DESERT_B2_N = auto()
    SUNKEN_DESERT_B2_W = auto()
    SUNKEN_DESERT_B2_SW = auto()
    SUNKEN_DESERT_B2_SE = auto()
    SUNKEN_DESERT_B2_E = auto()
    SUNKEN_DESERT_B2_CENTER = auto()
    MAGUS_CASTLE_GUILLOTINE_1 = auto()
    MAGUS_CASTLE_GUILLOTINE_2 = auto()
    MAGUS_CASTLE_SLASH_ROOM_1 = auto()
    MAGUS_CASTLE_SLASH_ROOM_2 = auto()
    MAGUS_CASTLE_STATUE_HALL = auto()
    MAGUS_CASTLE_FOUR_KIDS = auto()
    MAGUS_CASTLE_OZZIE_1 = auto()
    MAGUS_CASTLE_OZZIE_2 = auto()
    MAGUS_CASTLE_ENEMY_ELEVATOR = auto()
    REPTITE_LAIR_SECRET_B2_NE_RIGHT = auto()
    LAB_32_RACE_LOG = auto()
    FACTORY_RUINS_GENERATOR = auto()
    DEATH_PEAK_SOUTH_FACE_KRAKKER = auto()
    DEATH_PEAK_SOUTH_FACE_SPAWN_SAVE = auto()
    DEATH_PEAK_SOUTH_FACE_SUMMIT = auto()
    DEATH_PEAK_FIELD = auto()
    DEATH_PEAK_KRAKKER_PARADE = auto()
    DEATH_PEAK_CAVES_LEFT = auto()
    DEATH_PEAK_CAVES_CENTER = auto()
    DEATH_PEAK_CAVES_RIGHT = auto()
    REPTITE_LAIR_SECRET_B1_SW = auto()
    REPTITE_LAIR_SECRET_B1_NE = auto()
    REPTITE_LAIR_SECRET_B1_SE = auto()
    REPTITE_LAIR_SECRET_B2_SE_RIGHT = auto()
    REPTITE_LAIR_SECRET_B2_NE_OR_SE_LEFT = auto()
    REPTITE_LAIR_SECRET_B2_SW = auto()
    TYRANO_LAIR_THRONE_1 = auto()
    TYRANO_LAIR_THRONE_2 = auto()
    # TYRANO_LAIR_THRONE Unused
    TYRANO_LAIR_TRAPDOOR = auto()
    TYRANO_LAIR_KINO_CELL = auto()
    # TYRANO_LAIR Unused? : 0xB7
    TYRANO_LAIR_MAZE_1 = auto()
    TYRANO_LAIR_MAZE_2 = auto()
    TYRANO_LAIR_MAZE_3 = auto()
    TYRANO_LAIR_MAZE_4 = auto()
    # 0xBC - 0xCF - BLACK_OMEN
    BLACK_OMEN_AUX_COMMAND_MID = auto()
    BLACK_OMEN_AUX_COMMAND_NE = auto()
    BLACK_OMEN_GRAND_HALL = auto()
    BLACK_OMEN_NU_HALL_NW = auto()
    BLACK_OMEN_NU_HALL_W = auto()
    BLACK_OMEN_NU_HALL_SW = auto()
    BLACK_OMEN_NU_HALL_NE = auto()
    BLACK_OMEN_NU_HALL_E = auto()
    BLACK_OMEN_NU_HALL_SE = auto()
    BLACK_OMEN_ROYAL_PATH = auto()
    BLACK_OMEN_RUMINATOR_PARADE = auto()
    BLACK_OMEN_EYEBALL_HALL = auto()
    BLACK_OMEN_TUBSTER_FLY = auto()
    BLACK_OMEN_MARTELLO = auto()
    BLACK_OMEN_ALIEN_SW = auto()
    BLACK_OMEN_ALIEN_NE = auto()
    BLACK_OMEN_ALIEN_NW = auto()
    BLACK_OMEN_TERRA_W = auto()
    BLACK_OMEN_TERRA_ROCK = auto()
    BLACK_OMEN_TERRA_NE = auto()
    OCEAN_PALACE_MAIN_S = auto()
    OCEAN_PALACE_MAIN_N = auto()
    OCEAN_PALACE_E_ROOM = auto()
    OCEAN_PALACE_W_ROOM = auto()
    OCEAN_PALACE_SWITCH_NW = auto()
    OCEAN_PALACE_SWITCH_SW = auto()
    OCEAN_PALACE_SWITCH_NE = auto()
    OCEAN_PALACE_SWITCH_SECRET = auto()
    OCEAN_PALACE_FINAL = auto()
    # FACTORY_RUINS_UNUSED: 0xE7
    MAGUS_CASTLE_LEFT_HALL = auto()
    MAGUS_CASTLE_UNSKIPPABLES = auto()
    MAGUS_CASTLE_PIT_E = auto()
    MAGUS_CASTLE_PIT_NE = auto()
    MAGUS_CASTLE_PIT_NW = auto()
    MAGUS_CASTLE_PIT_W = auto()
    # GIANTS_CLAW_MAZE Unused: 0xF7
    # DEATH_PEAK_CLIFF Unused: 0xF8
    # Weird ones
    TABAN_GIFT_SUIT = auto()
    TABAN_GIFT_HELM = auto()
    TRADING_POST_RANGED_WEAPON = auto()
    TRADING_POST_ACCESSORY = auto()
    TRADING_POST_TAB = auto()
    TRADING_POST_MELEE_WEAPON = auto()
    TRADING_POST_ARMOR = auto()
    TRADING_POST_HELM = auto()
    JERKY_GIFT = auto()
    # Rocks not in chests
    DENADORO_ROCK = auto()
    KAJAR_ROCK = auto()
    LARUBA_ROCK = auto()

    BEKKLER_KEY = auto()
    CYRUS_GRAVE_KEY = auto()
    SUN_KEEP_2300 = auto()
    LUCCA_WONDERSHOT = auto()
    TABAN_SUNSHADES = auto()
    FAIR_PENDANT = auto()
    TATA_REWARD = auto()
    TOMA_REWARD = auto()
    MELCHIOR_FORGE_MASA = auto()
    EOT_GASPAR_REWARD = auto()
    HUNTING_RANGE_NU_REWARD = auto()
    ZEAL_MAMMON_MACHINE = auto()
    MAGUS_CASTLE_SLASH_SWORD_FLOOR = auto()
    GUARDIA_PRISON_LUNCH_BAG = auto()
    CRONOS_MOM = auto()
    TRUCE_MAYOR_2F_OLD_MAN = auto()

    # Tabs
    # Tabs later if they're going to be randomized
    GUARDIA_FOREST_POWER_TAB_600 = auto()
    GUARDIA_FOREST_POWER_TAB_1000 = auto()
    MANORIA_CONFINEMENT_POWER_TAB = auto()
    DORINO_BROMIDE_MAGIC_TAB = auto()
    PORRE_MARKET_600_POWER_TAB = auto()
    DENADORO_MTS_SPEED_TAB = auto()
    TOMAS_GRAVE_SPEED_TAB = auto()
    GIANTS_CLAW_CAVERNS_POWER_TAB = auto()
    GIANTS_CLAW_ENTRANCE_POWER_TAB = auto()
    GIANTS_CLAW_TRAPS_POWER_TAB = auto()
    SUN_KEEP_600_POWER_TAB = auto()
    MEDINA_ELDER_SPEED_TAB = auto()
    MEDINA_ELDER_MAGIC_TAB = auto()
    MAGUS_CASTLE_FLEA_MAGIC_TAB = auto()
    MAGUS_CASTLE_DUNGEONS_MAGIC_TAB = auto()
    TRANN_DOME_SEALED_MAGIC_TAB = auto()
    ARRIS_DOME_SEALED_POWER_TAB = auto()
    KEEPERS_DOME_MAGIC_TAB = auto()
    DEATH_PEAK_POWER_TAB = auto()
    BLACKBIRD_DUCTS_MAGIC_TAB = auto()
    GENO_DOME_ATROPOS_MAGIC_TAB = auto()
    GENO_DOME_CORRIDOR_POWER_TAB = auto()
    GENO_DOME_LABS_MAGIC_TAB = auto()
    GENO_DOME_LABS_SPEED_TAB = auto()
    ENHASA_NU_BATTLE_MAGIC_TAB = auto()
    ENHASA_NU_BATTLE_SPEED_TAB = auto()
    KAJAR_SPEED_TAB = auto()
    KAJAR_NU_SCRATCH_MAGIC_TAB = auto()
    LAST_VILLAGE_NU_SHOP_MAGIC_TAB = auto()
    SUNKEN_DESERT_POWER_TAB = auto()
    MOUNTAINS_RE_NICE_MAGIC_TAB = auto()
    BEAST_NEST_POWER_TAB = auto()
    MT_WOE_MAGIC_TAB = auto()
    OCEAN_PALACE_ELEVATOR_MAGIC_TAB = auto()
    OZZIES_FORT_GUILLOTINES_TAB = auto()
    PROTO_DOME_PORTAL_TAB = auto()


class EnemyID(StrIntEnum):
    """Enumeration of enemy IDs"""

    # Bosses first
    KRAWLIE = 0x04
    YAKRA = 0x90
    TWIN_BOSS = 0x4F
    MASA_MUNE = 0x99
    NIZBEL = 0x9B
    NIZBEL_II = 0x9C
    SLASH = 0x9D
    SLASH_SWORD = 0x9E
    FLEA = 0x9F
    DALTON = 0xA1
    DALTON_PLUS = 0xA2
    SUPER_SLASH = 0xBA
    HECKRAN = 0xA9
    FLEA_PLUS = 0xBB
    RUST_TYRANO = 0xBD
    ATROPOS_XR = 0xC0
    YAKRA_XIII = 0xC7
    GOLEM = 0x95
    GOLEM_BOSS = 0xF3
    ZOMBOR_BOTTOM = 0xB3
    ZOMBOR_TOP = 0xB4
    LAVOS_SPAWN_SHELL = 0xD7
    LAVOS_SPAWN_HEAD = 0xD8
    MEGA_MUTANT_HEAD = 0xB8
    MEGA_MUTANT_BOTTOM = 0xB9
    GIGA_MUTANT_HEAD = 0x35
    GIGA_MUTANT_BOTTOM = 0x36
    TERRA_MUTANT_HEAD = 0x37
    TERRA_MUTANT_BOTTOM = 0x38
    ELDER_SPAWN_SHELL = 0x6F
    ELDER_SPAWN_HEAD = 0x6E
    RETINITE_EYE = 0x3A
    RETINITE_TOP = 0xB6
    RETINITE_BOTTOM = 0xB5
    SON_OF_SUN_EYE = 0xF6
    SON_OF_SUN_FLAME = 0xF7
    # Normal Enemies
    NU = 0x00
    REPTITE_GREEN = 0x01
    TERRASAUR = 0x02
    KILWALA = 0x03
    # KRAWLIE = 0x04
    HENCH_PURPLE = 0x05
    OMICRONE = 0x06
    MARTELLO = 0x07
    BELLBIRD = 0x08
    PANEL = 0x09
    MAMMON_M = 0x0A
    LAVOS_3_CENTER_UNK_0B = 0x0B
    BLUE_IMP = 0x0C
    GREEN_IMP = 0x0D
    STONE_IMP = 0x0E
    MUD_IMP = 0x0F
    ROLY = 0x10
    POLY = 0x11
    ROLYPOLY = 0x12
    ROLY_RIDER = 0x13
    LAVOS_GIGA_GAIA_RIGHT = 0x14
    BLUE_EAGLET = 0x15
    GOLD_EAGLET = 0x16
    RED_EAGLET = 0x17
    LAVOS_GIGA_GAIA_LEFT = 0x18
    AVIAN_CHAOS = 0x19
    IMP_ACE = 0x1A
    BANTAM_IMP = 0x1B
    GNASHER = 0x1C
    GNAWER = 0x1D
    NAGA_ETTE = 0x1E
    LAVOS_SUPPORT_UNK_1F = 0x1F
    RUMINATOR = 0x20
    LAVOS_SUPPORT_UNK_21 = 0x21
    OCTOPOD = 0x22
    OCTOBLUSH = 0x23
    OCTOBINO = 0x24
    ZEAL = 0x25
    FLY_TRAP = 0x26
    MEAT_EATER = 0x27
    MAN_EATER = 0x28
    KRAKKER = 0x29
    EGDER = 0x2A
    DEFUNCT = 0x2B
    DEPARTED = 0x2C
    DECEASED = 0x2D
    DECEDENT = 0x2E
    MACABRE = 0x2F
    REAPER = 0x30
    GUARD = 0x31
    SENTRY = 0x32
    FREE_LANCER = 0x33
    OUTLAW = 0x34
    # GIGA_MUTANT = 0x35
    #  = 0x36
    # TERRAMUTANT = 0x37
    #  = 0x38
    JUGGLER = 0x39
    RETINITE = 0x3A
    MAGE = 0x3B
    UNKNOWN_3C = 0x3C
    REPTITE_PURPLE = 0x3D
    BLUE_SHIELD = 0x3E
    YODU_DE = 0x3F
    INCOGNITO = 0x40
    PEEPINGDOOM = 0x41
    BOSS_ORB = 0x42
    SIDE_KICK = 0x43
    UNKNOWN_44 = 0x44
    JINN_BOTTLE = 0x45
    EVILWEEVIL = 0x46
    TEMPURITE = 0x47
    DIABLOS = 0x48
    GARGOYLE = 0x49
    GRIMALKIN = 0x4A
    HENCH_BLUE = 0x4B
    T_POLE = 0x4C
    CROAKER = 0x4D
    AMPHIBITE = 0x4E
    # BULL_FROG = 0x4F  # Changed to a Golem
    MAD_BAT = 0x50
    VAMP = 0x51
    SCOUTER = 0x52
    FLYCLOPS = 0x53
    BUGGER = 0x54
    DEBUGGER = 0x55
    DEBUGGEST = 0x56
    SORCERER = 0x57
    JINN = 0x58
    BARGHEST = 0x59
    UNKNOWN_5A = 0x5A
    CRATER = 0x5B
    VOLCANO = 0x5C
    SHITAKE = 0x5D
    HETAKE = 0x5E
    RUBBLE = 0x5F
    UNKNOWN_60 = 0x60
    SHIST = 0x61
    PAHOEHOE = 0x62
    NEREID = 0x63
    SAVE_POINT_ENEMY = 0x64
    MOHAVOR = 0x65
    SHADOW = 0x66
    LAVOS_SUPPORT_UNK_67 = 0x67
    BASE = 0x68
    ACID = 0x69
    ALKALINE = 0x6A
    ION = 0x6B
    ANION = 0x6C
    THRASHER = 0x6D
    # = 0x6E
    # LAVOS_SPAWN = 0x6F
    LASHER = 0x70
    GOBLIN = 0x71
    OGRE = 0x72
    CAVE_BAT = 0x73
    OGAN = 0x74
    FLUNKY = 0x75
    GROUPIE = 0x76
    LAVOS_SUPPORT_UNK_77 = 0x77
    LAVOS_SUPPORT_UNK_78 = 0x78
    WINGED_APE = 0x79
    CAVE_APE = 0x7A
    MEGASAUR = 0x7B
    OMNICRONE = 0x7C
    BEAST = 0x7D
    BLUE_BEAST = 0x7E
    RED_BEAST = 0x7F
    TURRET = 0x80
    LIZARDACTYL = 0x81
    NU_2 = 0x82
    AVIAN_REX = 0x83
    BLOB = 0x84
    ALIEN = 0x85
    RAT = 0x86
    GREMLIN = 0x87
    RUNNER = 0x88
    PROTO_2 = 0x89
    PROTO_3 = 0x8A
    PROTO_4 = 0x8B
    BUG = 0x8C
    BEETLE = 0x8D
    GOON = 0x8E
    CYRUS = 0x8F
    # YAKRA = 0x90
    RAIN_FROG = 0x91
    GATO = 0x92
    DRAGON_TANK = 0x93
    GRINDER = 0x94
    # GOLEM = 0x95
    SYNCHRITE = 0x96
    MASA = 0x97
    MUNE = 0x98
    # MASA_MUNE = 0x99
    AZALA = 0x9A
    # NIZBEL = 0x9B
    # NIZBEL_II = 0x9C
    # SLASH = 0x9D
    # SLASH = 0x9E
    # FLEA = 0x9F
    FLEA_PLUS_TRIO = 0xA0
    # DALTON = 0xA1
    # DALTON_PLUS = 0xA2
    MUTANT = 0xA3
    METAL_MUTE = 0xA4
    SUPER_SLASH_TRIO = 0xA5
    OZZIE_ZENAN = 0xA6
    OZZIE_FORT = 0xA7
    GREAT_OZZIE = 0xA8
    # HECKRAN = 0xA9
    GIGASAUR = 0xAA
    LEAPER = 0xAB
    FOSSIL_APE = 0xAC
    TANK_HEAD = 0xAD
    DECEDENT_II = 0xAE
    OCTORIDER = 0xAF
    ZEAL_2_CENTER = 0xB0
    ZEAL_2_LEFT = 0xB1
    ZEAL_2_RIGHT = 0xB2
    # ZOMBOR = 0xB3
    #  = 0xB4
    #  = 0xB5  # RETINITE
    #  = 0xB6
    DISPLAY = 0xB7
    # MEGA_MUTANT = 0xB8
    #  = 0xB9
    # SUPER_SLASH = 0xBA
    # FLEA_PLUS = 0xBB
    BLACKTYRANO = 0xBC
    # RUST_TYRANO = 0xBD
    MOTHERBRAIN = 0xBE
    UNKNOWN_BF = 0xBF
    # ATROPOS_XR = 0xC0
    CYBOT = 0xC1
    LAVOS_GUARDIAN = 0xC2
    LAVOS_HECKRAN = 0xC3
    LAVOS_ZOMBOR_UPPER = 0xC4
    LAVOS_MASA_MUNE = 0xC5
    LAVOS_NIZBEL = 0xC6
    # YAKRA_XIII = 0xC7
    TUBSTER = 0xC8
    LAVOS_MAGUS = 0xC9
    LAVOS_TANK_HEAD = 0xCA
    LAVOS_2_HEAD = 0xCB
    LAVOS_2_LEFT = 0xCC
    LAVOS_2_RIGHT = 0xCD
    LAVOS_3_CORE = 0xCE
    GUARDIAN_BIT = 0xCF
    GUARDIAN_BYTE = 0xD0
    GIGA_GAIA_HEAD = 0xD1
    GIGA_GAIA_LEFT = 0xD2
    GIGA_GAIA_RIGHT = 0xD3
    GUARDIAN = 0xD4
    RED_SCOUT = 0xD5
    BLUE_SCOUT = 0xD6
    # LAVOS_SPAWN = 0xD7
    #  = 0xD8
    LASER_GUARD = 0xD9
    LAVOS_TANK_LEFT = 0xDA
    LAVOS_TANK_RIGHT = 0xDB
    LAVOS_GUARDIAN_LEFT = 0xDC
    LAVOS_GUARDIAN_RIGHT = 0xDD
    LAVOS_ZOMBOR_BOTTOM = 0xDE
    LAVOS_TYRANO_AZALA = 0xDF
    SPEKKIO_FROG = 0xE0
    SPEKKIO_KILWALA = 0xE1
    SPEKKIO_OGRE = 0xE2
    SPEKKIO_OMNICRONE = 0xE3
    SPEKKIO_MASA_MUNE = 0xE4
    SPEKKIO_NU = 0xE5
    LAVOS_TYRANO = 0xE6
    LAVOS_GIGA_GAIA_HEAD = 0xE7
    LAVOS_UNK_E8 = 0xE8
    LAVOS_UNK_E9 = 0xE9
    LAVOS_UNK_EA = 0xEA
    LAVOS_OCEAN_PALACE = 0xEB
    LAVOS_1 = 0xEC
    LAVOS_3_LEFT = 0xED
    HEXAPOD = 0xEE
    LAVOS_3_RIGHT = 0xEF
    FAKE_FLEA = 0xF0
    OZZIE_MAGUS_CHAINS = 0xF1
    ROLY_BOMBER = 0xF2
    # GOLEM_BOSS = 0xF3
    JOHNNY = 0xF4
    BASHER = 0xF5
    # SON_OF_SUN = 0xF6
    #  = 0xF7
    R_SERIES = 0xF8
    MAGUS = 0xF9
    MAGUS_NORTH_CAPE = 0xFA
    MAGUS_NO_NAME = 0xFB
    UNUSED_FC = 0xFC
    UNUSED_FD = 0xFD
    UNUSED_FE = 0xFE
    UNUSED_FF = 0xFF


class ShopID(Enum):
    MELCHIOR_FAIR = 0x00
    TRUCE_MARKET_600 = 0x01
    TRUCE_MARKET_1000 = 0x02
    ARRIS_DOME = 0x03
    MELCHIORS_HUT = 0x04
    DORINO = 0x05
    PORRE_600 = 0x06
    LAST_VILLAGE = 0x07
    IOKA_VILLAGE = 0x08
    LAST_VILLAGE_UPDATED = 0x09
    NU_NORMAL_KAJAR = 0x0A
    ENHASA = 0x0B
    PORRE_1000 = 0x0C
    EARTHBOUND_VILLAGE = 0x0D
    CHORAS_INN_1000 = 0x0E
    CHORAS_MARKET_600 = 0x0F
    MILENNIAL_FAIR_ARMOR = 0x10
    MILLENIAL_FAIR_ITEMS = 0x11
    EMPTY_12 = 0x12
    TRANN_DOME = 0x13
    EMPTY_14 = 0x14
    MEDINA_MARKET = 0x15
    FIONAS_SHRINE = 0x16
    NU_BLACK_OMEN = 0x17
    # There is room for shops through 0x3F if desired


class RecruitID(StrIntEnum):
    STARTER = auto()
    CATHEDRAL = auto()
    CASTLE = auto()
    MILLENNIAL_FAIR = auto()
    DACTYL_NEST = auto()
    PROTO_DOME = auto()
    FROGS_BURROW = auto()
    CRONO_TRIAL = auto()
    DEATH_PEAK = auto()
    NORTH_CAPE = auto()


class Element(StrIntEnum):
    LIGHTNING = auto()
    FIRE = auto()
    SHADOW = auto()
    ICE = auto()
    NONELEMENTAL = auto()


class TechID(StrIntEnum):
    """Enumeration of vanilla tech IDs"""

    NONE = 0
    CYCLONE = 1
    SLASH = 2
    LIGHTNING = 3
    SPINCUT = 4
    LIGHTNING_2 = 5
    LIFE = 6
    CONFUSE = 7
    LUMINAIRE = 8
    AURA = 9
    PROVOKE = 0xA
    ICE = 0xB
    CURE = 0xC
    HASTE = 0xD
    ICE_2 = 0xE
    CURE_2_M = 0xF
    LIFE_2_M = 0x10
    FLAME_TOSS = 0x11
    HYPNO_WAVE = 0x12
    FIRE = 0x13
    NAPALM = 0x14
    PROTECT = 0x15
    FIRE_2 = 0x16
    MEGABOMB = 0x17
    FLARE = 0x18
    ROCKET_PUNCH = 0x19
    CURE_BEAM = 0x1A
    LASER_SPIN = 0x1B
    ROBO_TACKLE = 0x1C
    HEAL_BEAM = 0x1D
    UZZI_PUNCH = 0x1E
    AREA_BOMB = 0x1F
    SHOCK = 0x20
    SLURP = 0x21
    SLURPCUT = 0x22
    WATER = 0x23
    HEAL = 0x24
    LEAP_SLASH = 0x25
    WATER_2 = 0x26
    CURE_2_F = 0x27
    FROGSQUASH = 0x28
    KISS = 0x29
    ROLLO_KICK = 0x2A
    CAT_ATTACK = 0x2B
    ROCK_THROW = 0x2C
    CHARM = 0x2D
    TAIL_SPIN = 0x2E
    DINO_TAIL = 0x2F
    TRIPLE_KICK = 0x30
    LIGHTNING_2_M = 0x31
    ICE_2_M = 0x32
    FIRE_2_M = 0x33
    DARK_BOMB = 0x34
    MAGIC_WALL = 0x35
    DARK_MIST = 0x36
    BLACK_HOLE = 0x37
    DARK_MATTER = 0x38
    AURA_WHIRL = 0x39
    ICE_SWORD = 0x3A
    ICE_SWORD_2 = 0x3B
    FIRE_WHIRL = 0x3C
    FIRE_SWORD = 0x3D
    FIRE_SWORD_2 = 0x3E
    ROCKET_ROLL = 0x3F
    MAX_CYCLONE = 0x40
    SUPER_VOLT = 0x41
    X_STRIKE = 0x42
    SWORD_STREAM = 0x43
    SPIRE = 0x44
    DRILL_KICK = 0x45
    VOLT_BITE = 0x46
    FALCON_HIT = 0x47
    ANTIPODE = 0x48
    ANTIPODE_2 = 0x49
    ANTIPODE_3 = 0x4A
    AURA_BEAM = 0x4B
    ICE_TACKLE = 0x4C
    CURE_TOUCH = 0x4D
    ICE_WATER = 0x4E
    GLACIER = 0x4F
    DOUBLE_CURE = 0x50
    TWIN_CHARM = 0x51
    ICE_TOSS = 0x52
    CUBE_TOSS = 0x53
    FIRE_PUNCH = 0x54
    FIRE_TACKLE = 0x55
    DOUBLE_BOMB = 0x56
    FLAME_KICK = 0x57
    BLAZE_TWISTER = 0x58
    BLAZE_KICK = 0x59
    BLADE_TOSS = 0x5A
    BUBBLE_SNAP = 0x5B
    CURE_WAVE = 0x5C
    BOOGIE = 0x5D
    SPIN_KICK = 0x5E
    BEAST_TOSS = 0x5F
    SLURP_KISS = 0x60
    BUBBLE_HIT = 0x61
    DROP_KICK = 0x62
    RED_PIN = 0x63
    LINE_BOMB = 0x64
    FROG_FLARE = 0x65
    DELTA_FORCE = 0x66
    LIFE_LINE = 0x67
    ARC_IMPULSE = 0x68
    GATLING_KICK = 0x69
    FIRE_ZONE = 0x6A
    DELTA_STORM = 0x6B
    FINAL_KICK = 0x6C
    TRIPLE_RAID = 0x6D
    TWISTER = 0x6E
    THREE_D_ATTACK = 0x6F
    DARK_ETERNAL = 0x70
    OMEGA_FLARE = 0x71
    SPIN_STRIKE = 0x72
    POYOZO_DANCE = 0x73
    GRAND_DREAM = 0x74


class StatusEffect(StrIntEnum):
    BLIND = 0x1
    SLEEP = 0x2
    CHAOS = 0x4
    LOCK = 0x8
    SLOW = 0x20
    POISON = 0x40
    STOP = 0x80


# structure of button bytes at 7e00{f6,f8,fa}, respects player rebound controls
# order is the order of the array in which the button mappings are stored
class ActionMap(StrIntEnum):
    CONFIRM = 0x80
    CANCEL = 0x08
    MENU = 0x40
    DASH = 0x02
    MAP = 0x04
    WARP = 0x01
    PG_UP = 0x10
    PG_DN = 0x20


# structure of button bytes at 7e00{f0,f2,f4}, does not respect player
# rebound controls
class InputMap(StrIntEnum):
    A_BUTTON = 0x80
    X_BUTTON = 0x40
    L_SHOULDER = 0x20
    R_SHOULDER = 0x10
    B_BUTTON = 0x08
    Y_BUTTON = 0x04
    SELECT_BUTTON = 0x02
    # START_BUTTON = 0x01 # Not allowed for rebinding controls


class ArmorEffects(StrIntEnum):
    """Enum of possible effects that can go on armor/helms."""

    NONE = 0x00
    SHIELD = 0x17
    ABSORB_LIT_25 = 0x1A
    ABSORB_SHD_25 = 0x1B
    ABSORB_WAT_25 = 0x1C
    ABSORB_FIR_25 = 0x1D
    ABSORB_LIT_100 = 0x1F
    ABSORB_SHD_100 = 0x20
    ABSORB_WAT_100 = 0x21
    ABSORB_FIR_100 = 0x22
    IMMUNE_CHAOS = 0x2A
    IMMUNE_LOCK = 0x2B
    IMMUNE_SLOW_STOP = 0x2C
    IMMUNE_ALL = 0x2D
    BARRIER = 0x31
    CHAOS_HP_DOWN = 0x32
    HASTE = 0x33
    BARRIER_SHIELD = 0x3B
    IMMUNE_ELEMENTS = 0x3C


class WeaponEffects(StrIntEnum):
    """Enum of possible effects that can go on weapons."""

    NONE = 0x00
    CRIT_X2 = 0x01
    WONDERSHOT = 0x02
    DMG_125 = 0x03
    DMG_150 = 0x04
    DMG_175 = 0x05
    DMG_200 = 0x06
    MAGIC = 0x07
    DMG_MAG_125 = 0x08
    DMG_MAG_150 = 0x09
    DMG_MAG_175 = 0x0A
    DMG_MAG_200 = 0x0B
    DMG_TO_MAG_150 = 0x0C
    DMG_TO_MAG_200 = 0x0D
    HP_TO_1 = 0x0E
    CHARM_80 = 0x0F
    CHARM_100 = 0x10
    CLEAR_STATUS = 0x11
    DMG_33 = 0x13
    DMG_25 = 0x14
    SLEEP_80_AQUA = 0x15
    DOOMSICKLE = 0x16
    HP_50_50 = 0x18
    CRISIS = 0x19
    HP_50_100 = 0x1E
    ATTACKER_DIES = 0x23
    DEATH_40 = 0x24
    DEATH_100 = 0x25
    STOP_60 = 0x26
    SLOW_60 = 0x27
    STOP_80_MACHINES = 0x28
    CHAOS_60 = 0x29
    CHAOS_80 = 0x2E
    CRIT_4X = 0x2F
    CLEAR_SHIELD_BARRIER = 0x30
    DMG_400 = 0x34
    CLEAR_IMMUNITY = 0x35
    RANDOM_STATUS = 0x36
    SLEEP = 0x37
    CRIT_9999 = 0x38
    VENUS_BOW = 0x39
    SPELLSLINGER = 0x3A


class NpcID(StrIntEnum):
    """Graphics IDs for NPCs"""
    MELCHIOR = 0x00
    KING_GUARDIA_1000 = 0x01
    # {02} Johnny
    # {03} Queen Leene
    # {04} Tata
    # {05} Toma
    # {06} Kino
    # {07} Chancellor (green) [1000 A.D.]
    # {08} Dactyl
    # {09} Schala
    # {0A} Janus
    # {0B} Chancellor (brown) [600 A.D.]
    # {0C} Belthasar
    # {0D} Middle Ages/Present Age villager - woman
    # {0E} Middle Ages/Present Age villager - young man
    # {0F} Middle Ages/Present Age villager - young woman
    # {10} Middle Ages/Present Age villager - soldier
    # {11} Middle Ages/Present Age villager - old man
    # {12} Middle Ages/Present Age villager - old woman
    # {13} Middle Ages/Present Age villager - little boy
    # {14} Middle Ages/Present Age villager - little girl
    # {15} Middle Ages/Present Age villager - waitress
    # {16} Middle Ages/Present Age villager - shopkeeper
    # {17} Nun
    # {18} Knight captain [600 A.D.]
    # {19} Middle Ages/Present Age villager - man
    # {1A} Dome survivor - man
    # {1B} Dome survivor - woman
    # {1C} Doan
    # {1D} Dome survivor - little girl
    # {1E} Prehistoric villager - man with club
    # {1F} Prehistoric villager - woman in green dress
    # {20} Prehistoric villager - little girl
    # {21} Prehistoric villager - old man
    # {22} Zeal citizen - man
    # {23} Zeal citizen - woman
    # {24} Zeal citizen - researcher with glasses
    # {25} Crono's mom
    CRONOS_MOM = 0x25
    # {26} Middle Ages/Present Age villager - little girl with purple hair
    # {27} Middle Ages/Present Age villager - man
    # {28} Middle Ages/Present Age villager - woman with purple hair
    # {29} Middle Ages/Present Age villager - young man
    # {2A} Middle Ages/Present Age villager - young woman
    # {2B} Middle Ages/Present Age villager - soldier
    # {2C} Middle Ages/Present Age villager - old man
    # {2D} Middle Ages/Present Age villager - old woman
    # {2E} Middle Ages/Present Age villager - little boy
    # {2F} Middle Ages/Present Age villager - little girl
    # {30} Middle Ages/Present Age villager - waitress with purple hair
    # {31} Middle Ages/Present Age villager - shopkeeper
    # {32} Nun
    # {33} Guardia knight [600 A.D.]
    # {34} Middle Ages/Present Age villager - man
    # {35} Cyrus
    # {36} Young Glenn
    # {37} King Guardia XXI [600 A.D.]
    # {38} Strength Test Machine part (Millennial Fair)
    # {39} Middle Ages/Present Age villager - old man (2C dupe/UNUSED)
    # {3A} Zeal citizen - researcher with glasses
    # {3B} Cat
    # {3C} False prophet Magus
    # {3D} Melchior in gray robe/UNUSED
    # {3E} Prehistoric villager - man carrying club with purple hair
    # {3F} Prehistoric villager - woman with purple hair
    # {40} Prehistoric villager - little girl with purple hair
    # {41} Algetty earthbound one - man
    # {42} Algetty earthbound one - woman
    # {43} Algetty earthbound one - old man
    # {44} Algetty earthbound one - child
    # {45} Princess Nadia
    # {46} Guardia Castle chef
    # {47} Trial judge
    # {48} Gaspar
    # {49} Fiona
    # {4A} Queen Zeal
    # {4B} Guard (enemy)
    # {4C} Reptite
    # {4D} Kilwala
    # {4E} Blue imp
    # {4F} Middle Ages/Present Age villager - man
    # {50} Middle Ages/Present Age villager - woman
    # {51} G.I. Jogger
    # {52} Millennial Fair visitor - old man
    # {53} Millennial Fair visitor - woman
    # {54} Millennial Fair visitor - little boy
    # {55} Millennial Fair visitor - little girl
    # {56} Lightning bolt
    # {57} Opened time portal - upper half
    # {58} Opened time portal - lower half
    # {59} Millennial Fair shopkeeper
    # {5A} Guillotine blade
    # {5B} Guillotine chain
    # {5C} Conveyor machine
    # {5D} Tombstone
    # {5E} Giant soup bowl
    # {5F} Magus statue
    DREAMSTONE = 0x60
    GATE_KEY = 0x61
    SODA_CAN = 0x62
    PENDANT = 0x63
    # {64} Poyozo doll
    # {65} Pink lunch bag
    # {66} UNUSED
    RED_KNIFE = 0x67
    BROKEN_BLADE = 0x68
    # {69} Slice of cake
    # {6A} Trash can on its side
    # {6B} Piece of cheese
    # {6C} Barrel
    # {6D} UNUSED
    MOONSTONE = 0x6E
    # {6F} Metal mug
    # {70} Blue star
    GIANT_BLUE_STAR = 0x71
    RED_FLAME = 0x72
    GIANT_RED_FLAME = 0x73
    # {74} Explosion ball
    # {75} Giant explosion ball
    # {76} Smoke trail/UNUSED
    HERO_MEDAL = 0x77
    # {78} Balcony shadow
    SAVE_POINT = 0x79
    # {7A} Prehistoric villager - drummer
    # {7B} Prehistoric villager - log drummer
    # {7C} White explosion outline
    # {7D} Leene's bell
    # {7E} Bat hanging upside down
    # {7F} Computer screen
    # {80} Water splash
    # {81} Explosion
    # {82} Robo power-up sparks
    # {83} Leaves falling/UNUSED
    # {84} 3 coins spinning/UNUSED
    # {85} Hole in the ground
    # {86} Cooking smoke
    # {87} 3 small explosion clouds
    # {88} Wind element spinning
    # {89} Water element/UNUSED
    # {8A} Dirt mound
    MASAMUNE_SPINNING = 0x8B
    # {8C} Music note/UNUSED
    # {8D} Small fish/UNUSED
    # {8E} Water splash/UNUSED
    # {8F} Lightning bolt/UNUSED
    # {90} Unknown graphics/UNUSED
    # {91} UNUSED
    SMALL_ROCK = 0x92
    # {93} Small rock *92 duplicate/UNUSED*
    # {94} Small rock *92 duplicate/UNUSED*
    RAINBOW_SHELL = 0x95
    # {96} Shadow (beds)
    CLOSED_PORTAL = 0x97
    # {98} Balloon/UNUSED
    # {99} Light green bush
    # {9A} Shadow on the ground/UNUSED
    # {9B} Brown dreamstone/UNUSED
    # {9C} Crane machine
    # {9D} UNUSED
    # {9E} Dripping water/UNUSED
    # {9F} Cupboard doors
    # {A0} Brown stones/UNUSED
    # {A1} Dark green bush
    # {A2} Journal
    # {A3} Norstein Bekkler
    # {A4} Rat
    # {A5} Sparks from guillotine blade
    # {A6} Zeal teleporter
    # {A7} Ocean palace teleporter
    # {A8} Truce Dome director
    # {A9} Epoch seats
    # {AA} Robot
    # {AB} Red star
    SEALED_PORTAL = 0xAC
    # {AD} Animated Zz (sleeping) icon
    FLYING_EPOCH_OW = 0xAE
    # {AF} Gray cat
    # {B0} Yellow cat
    # {B1} Alfador
    C_TRIGGER = 0x82
    # {B3} Zeal citizen - man (cast ending)
    # {B4} Zeal citizen - woman
    POTTED_PLANT = 0xB5
    # {B6} Kid with purple hair (Glenn/Cyrus cutscene)
    # {B7} Sealed chest
    # {B8} Squirrel (Programmer's Ending)
    # {B9} Blue poyozo
    # {BA} Stone rubble pile
    # {BB} Rusted Robo
    # {BC} Gaspar (Gurus cutscene)
    # {BD} UNUSED
    # {BE} Orange cat
    # {BF} Middle Ages/Present Age villager - little boy
    # {C0} Middle Ages/Present Age villager - little girl
    # {C1} Spinning water element
    # {C2} Blue shining star - small
    # {C3} Blue shining star - large
    # {C4} Multiple balloons
    # {C5} Dancing woman (Millennial Fair ending)
    # {C6} Millennial Fair visitor - little girl
    # {C7} Silver Leene's bell
    # {C8} Figure atop Magus' Castle (ending)
    # {C9} Serving tray with drinks
    # {CA} THE END text
    # {CB} Human Glenn (ending cutscene)
    # {CC} Queen Zeal (Death Peak cutscene)
    # {CD} Schala (Death Peak cutscene)
    # {CE} Lavos (Death Peak cutscene)
    # {CF} Crono (Death Peak cutscene)
    # {D0} Hironobu Sakaguchi (Programmer's Ending)
    # {D1} Yuji Horii (Programmer's Ending)
    # {D2} Akira Toriyama (Programmer's Ending)
    # {D3} Kazuhiko Aoki (Programmer's Ending)
    # {D4} Lightning flash
    # {D5} Lara
    # {D6} Purple explosion
    # {D7} Crono's mom (Millennial Fair ending)
    # {D8} UNUSED
    # {D9} UNUSED
    # {DA} UNUSED
    # {DB} UNUSED
    # {DC} UNUSED
    # {DD} UNUSED
    # {DE} UNUSED
    # {DF} UNUSED
    # {E0} Green balloon/UNUSED
    # {E1} Yellow balloon/UNUSED
    # {E2} Blue balloon/UNUSED
    # {E3} Pink balloon/UNUSED
    # {E4} Brown glowing light/UNUSED
    # {E5} Yellow glowing light/UNUSED
    # {E6} Purple glowing light/UNUSED
    # {E7} Blue glowing light
    # {E8} UNUSED
    # {E9} UNUSED
    # {EA} UNUSED
    # {EB} UNUSED
    # {EC} UNUSED
    # {ED} UNUSED
    # {EE} UNUSED
    # {EF} UNUSED
    # {F0} UNUSED
    # {F1} UNUSED
    # {F2} UNUSED
    # {F3} UNUSED
    # {F4} UNUSED
    # {F5} UNUSED
    # {F6} UNUSED
    # {F7} UNUSED
    # {F8} UNUSED
    # {F9} UNUSED
    # {FA} UNUSED
    # {FB} UNUSED
    # {FC} UNUSED
    # {FD} UNUSED
    # {FE} UNUSED
    # {FF} UNUSED
