# New beginner preset
xp_scale = 6.0
tp_scale = 5.0
split_tp = false
fix_tp_doubling = true
xp_penalty_level = 43
xp_penalty_percent = 25
level_cap = 55
use_tech_level_treasures = true
extra_tech_levels_per_char = 1
boss_xp_factor = 0.75
midboss_reward_factor = 1.0
normalize_boss_xp = true
normalize_enemies = false
show_all_chars_in_shop = true
drop_enemy_pool = "midbosses"
drop_reward_pool = "shuffle"
drop_rate = 1.0
custom_drop_reward_pool = [ "speed_tab", "power_tab", "magic_tab", "red_vest", "blue_vest", "white_vest", "black_vest", "silverstud", "slasher", "elixir", "vedicblade", "megablast", "sonicarrow", "kaiser_arm", "big_hand", "pearl_edge", "demon_hit", "hurricane", "aeon_helm", "power_seal", "magic_seal", "silvererng", "frenzyband", "hyperether", "full_tonic", "speed_belt", "taban_vest", "speed_tab", "power_tab", "magic_tab",]
drop_enemy_pool_2 = "bosses"
drop_reward_pool_2 = "shuffle"
drop_rate_2 = 1.0
custom_drop_enemy_pool_2 = [ "zombor_top", "lavos_spawn_shell", "mega_mutant_bottom", "giga_mutant_bottom", "terra_mutant_bottom", "elder_spawn_head", "retinite_bottom", "lavos_3_core", "guardian_bit", "display", "giga_gaia_left", "giga_gaia_right", "grinder", "tank_head",]
custom_drop_reward_pool_2 = [ "speed_tab", "power_tab", "magic_tab", "sight_cap", "red_mail", "blue_mail", "white_mail", "black_mail", "silverstud", "gold_stud", "swallow", "elixir", "megaelixir", "slasher_2", "sonicarrow", "sonicarrow", "megablast", "cometarrow", "cometarrow", "big_hand", "giga_arm", "rune_blade", "pearl_edge", "pearl_edge", "demon_hit", "hurricane", "memory_cap", "time_hat", "aeon_helm", "power_seal", "magic_seal", "wall_ring", "silvererng", "frenzyband", "rbow_helm", "mermaidcap", "dark_helm", "dash_ring", "taban_suit", "speed_tab", "power_tab", "magic_tab", "sight_cap", "red_mail", "blue_mail", "white_mail", "black_mail", "silverstud", "swallow", "elixir", "megaelixir", "slasher_2", "megablast", "big_hand", "giga_arm", "rune_blade", "demon_hit", "hurricane", "memory_cap", "time_hat", "aeon_helm", "power_seal", "magic_seal", "wall_ring", "silvererng", "frenzyband", "rbow_helm", "mermaidcap", "dark_helm", "vigil_hat", "gold_erng", "sun_shades", "dash_ring", "taban_suit", "speed_tab", "power_tab", "magic_tab",]
drop_enemy_pool_3 = "normal_enemies"
drop_reward_pool_3 = "random"
drop_rate_3 = 0.75
custom_drop_reward_pool_3 = [ "power_tab", "magic_tab", "silverstud", "rage_band", "bandana", "shelter", "shelter", "shelter", "mid_tonic", "mid_tonic", "mid_tonic", "ether", "ether", "ether", "mid_ether", "power_meal", "power_meal", "power_meal", "fangs_2", "fangs_2", "feathers_2", "feathers_2", "petals_2", "petals_2", "horns_2", "horns_2", "tonic", "tonic", "tonic", "revive", "revive", "revive", "heal", "heal", "heal", "lapis", "shield", "barrier", "red_katana", "aeon_blade", "robin_bow", "sage_bow", "plasma_gun", "ruby_gun", "stone_arm", "magma_hand", "flashblade", "ruby_vest", "meso_mail", "lumin_robe", "dark_mail", "ceratopper", "taban_helm", "magicscarf", "berserker", "hit_ring", "power_ring", "magic_ring",]
drop_enemy_pool_4 = "hard_enemies"
drop_reward_pool_4 = "random"
drop_rate_4 = 1.0
custom_drop_reward_pool_4 = [ "power_tab", "magic_tab", "speed_tab", "silverstud", "frenzyband", "speed_belt", "full_tonic", "full_ether", "hyperether", "elixir", "lapis", "shield", "barrier", "megablast", "sonicarrow", "rune_blade", "giga_arm", "hurricane", "demon_edge", "star_sword", "cometarrow", "kali_blade", "megablast", "demon_hit", "big_hand", "white_vest", "black_vest", "blue_vest", "red_vest", "lode_vest", "aeon_suit", "taban_vest", "lode_helm", "aeon_helm", "dark_helm", "rbow_helm", "mermaidcap", "power_seal", "magic_seal", "silvererng", "silverstud", "dragon_tear", "power_tab", "magic_tab", "speed_tab", "power_tab", "magic_tab", "speed_tab", "full_tonic", "full_ether", "hyperether", "elixir", "lapis",]
mark_dropping_enemies = false
charm_enemy_pool = "all"
charm_reward_pool = "vanilla"
charm_rate = 1.0
mark_charmable_enemies = false
tech_order = "mp_type"
tech_damage = "shuffle"
tech_damage_random_factor_min = 1.0
tech_damage_random_factor_max = 1.2
normalize_techs = true
preserve_magic = false
black_hole_factor = 3.0
black_hole_min = 40.0
show_full_tech_list = true
balance_tech_mps = true
custom_damage_mps = [ 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 8, 8, 8, 8, 8, 8, 8, 8, 10, 10, 10, 10, 12, 12, 14, 15, 15, 15, 15, 17, 20, 20, 20, 20,]
dynamic_scaling_scheme = "progression"
levels_per_boss = 3.0
levels_per_quest = 0.0
levels_per_key_item = 1.0
levels_per_objective = 2.0
levels_per_character = 1.0
max_scaling_level = 50
dynamic_scale_lavos = false
dynamic_scale_lavos_gauntlet = false
defense_safety_min_level = 10
defense_safety_max_level = 30
obstacle_safety_level = 30
normal_enemy_hp_scale = 1.0
static_boss_hp_scale = 1.0
static_hp_scale_lavos = false
element_safety_level = 30
millennial_fair_mod = 0
guardia_forest_1000_mod = 0
guardia_forest_600_mod = 0
crono_trial_mod = -3
heckran_cave_mod = 0
truce_canyon_mod = 0
manoria_cathedral_mod = 0
denadoro_mountains_mod = 0
cursed_woods_mod = 0
lab_16_mod = 0
lab_32_mod = 0
sewers_mod = 0
death_peak_mod = 0
arris_dome_mod = 0
proto_dome_mod = 0
factory_ruins_mod = 0
mystic_mountains_mod = 0
hunting_range_mod = 0
dactyl_nest_mod = 0
shell_trial_mod = 0
zenan_bridge_mod = 0
northern_ruins_mod = 0
giants_claw_mod = 0
ozzies_fort_mod = 0
magus_castle_mod = 0
magic_cave_mod = 0
sunken_desert_mod = 0
sun_palace_mod = 0
geno_dome_mod = 0
forest_maze_mod = 0
reptite_lair_mod = 0
tyrano_lair_mod = 0
black_omen_mod = 0
north_cape_mod = 0
epoch_battle_mod = 0
blackbird_mod = 0
enhasa_mod = 0
ocean_palace_mod = 0
mt_woe_mod = 0
additional_key_items = [ "masamune_2",]
forced_spots = [ "melchior_forge_masa", "zenan_bridge_captain", "death_peak_south_face_summit", "sun_palace_key", "bekkler_key", "fair_pendant", "zeal_mammon_machine", "mt_woe_key", "giants_claw_key", "kings_trial_key", "yakras_room", "snail_stop_key", "denadoro_mts_key", "frogs_burrow_left", "cyrus_grave_key", "tata_reward", "fiona_key", "sun_keep_2300", "jerky_gift", "arris_dome_doan_key", "arris_dome_food_locker_key", "reptite_lair_key", "taban_gift_vest", "geno_dome_boss_1", "courtroom_yakra_key",]
loose_key_items = [ "sun_stone", "race_log",]
incentive_spots = []
incentive_factor = 5.0
excluded_spots = [ "trading_post_petal_fang_base", "trading_post_petal_fang_upgrade", "trading_post_petal_horn_base", "trading_post_petal_horn_upgrade", "trading_post_petal_feather_base", "trading_post_petal_feather_upgrade", "trading_post_fang_horn_base", "trading_post_fang_horn_upgrade", "trading_post_fang_feather_base", "trading_post_fang_feather_upgrade", "trading_post_horn_feather_base", "trading_post_horn_feather_upgrade", "reptite_lair_secret_b2_ne_right", "reptite_lair_secret_b1_sw", "reptite_lair_secret_b1_ne", "reptite_lair_secret_b1_se", "reptite_lair_secret_b2_se_right", "reptite_lair_secret_b2_ne_or_se_left", "reptite_lair_secret_b2_sw", "black_omen_aux_command_mid", "black_omen_aux_command_ne", "black_omen_grand_hall", "black_omen_nu_hall_nw", "black_omen_nu_hall_w", "black_omen_nu_hall_sw", "black_omen_nu_hall_ne", "black_omen_nu_hall_e", "black_omen_nu_hall_se", "black_omen_royal_path", "black_omen_ruminator_parade", "black_omen_eyeball_hall", "black_omen_tubster_fly", "black_omen_martello", "black_omen_alien_sw", "black_omen_alien_ne", "black_omen_alien_nw", "black_omen_terra_w", "black_omen_terra_rock", "black_omen_terra_ne", "ocean_palace_elevator_magic_tab", "blackbird_ducts_magic_tab", "last_village_nu_shop_magic_tab",]
decay_factor = 1.0
starter_rewards = [ "iron_blade", "dart_gun", "hammer_arm", "iron_sword", "iron_bow", "pacifist", "pacifist", "epoch",]
out_of_logic_starter_rewards = []
hard_lavos_end_boss = false
boats_of_time = false
jets_of_time = true
min_flight_depth = 0
lock_gates = false
disable_element_locks = true
boss_randomization_type = "shuffle"
midboss_randomization_type = "shuffle"
vanilla_boss_spots = []
boss_pool = [ "dalton_plus", "elder_spawn", "flea", "giga_mutant", "golem", "golem_boss", "heckran", "lavos_spawn", "masa_mune", "mega_mutant", "mud_imp", "nizbel", "nizbel_2", "retinite", "r_series", "rust_tyrano", "slash_sword", "son_of_sun", "terra_mutant", "yakra", "yakra_xiii", "zombor", "mother_brain", "dragon_tank", "giga_gaia", "guardian",]
midboss_pool = [ "gato", "dalton", "krawlie", "super_slash", "flea_plus", "atropos_xr",]
shop_inventory_randomization = "tiered_random"
shop_capacity_randomization = "random"
guaranteed_shop_items = [ "power_tab", "magic_tab", "speed_tab",]
not_buyable_items = [ "hide_tunic", "karate_gi", "bronzemail", "hide_cap", "bronzehelm", "maidensuit", "iron_suit", "iron_helm", "beret", "bucketfrag", "petals_2", "feathers_2", "horns_2", "fangs_2", "masamune_1", "masamune_2", "bent_hilt", "bent_sword", "hero_medal", "seed", "bike_key", "pendant", "gate_key", "prismshard", "c_trigger", "tools", "jerky", "race_log", "moon_stone", "sun_stone", "ruby_knife", "yakra_key", "clone", "tomas_pop", "pendant_charge", "rainbow_shell", "jetsoftime", "dreamstone",]
not_sellable_items = [ "masamune_1", "masamune_2", "bent_hilt", "bent_sword", "hero_medal", "seed", "bike_key", "pendant", "gate_key", "prismshard", "c_trigger", "tools", "jerky", "race_log", "moon_stone", "sun_stone", "ruby_knife", "yakra_key", "clone", "tomas_pop", "petals_2", "fangs_2", "horns_2", "feathers_2", "pendant_charge", "rainbow_shell", "jetsoftime", "dreamstone",]
item_base_prices = "balanced"
item_price_randomization = "random_multiplier"
item_price_min_multiplier = 0.5
item_price_max_multiplier = 1.0
num_algetty_portal_objectives = 2
num_omen_objectives = 2
num_bucket_objectives = 4
num_gauntlet_objectives = 0
num_timegauge_objectives = 5
no_omen_gauntlet = true
objective_1 = "any_quest"
objective_2 = "any_quest"
objective_3 = "any_quest"
objective_4 = "any_quest"
objective_5 = "any_quest"
objective_6 = "any_quest"
objective_7 = "any_quest"
objective_8 = "any_quest"
shuffle_entrances = false
block_zenan_600 = false
block_zenan_1000 = false
preserve_spots = []
rest_vanilla = true
shuffle_gates = false
separate_gate_eras = true
starter_min_level = 3
starter_min_techlevel = 1
fair_min_level = 1
fair_min_techlevel = 1
cathedral_min_level = 5
cathedral_min_techlevel = 1
castle_min_level = 5
castle_min_techlevel = 2
trial_min_level = 7
trial_min_techlevel = 2
proto_min_level = 10
proto_min_techlevel = 2
north_cape_min_level = 37
north_cape_min_techlevel = 3
burrow_min_level = 18
burrow_min_techlevel = 3
dactyl_min_level = 20
dactyl_min_techlevel = 3
death_peak_min_level = 37
death_peak_min_techlevel = 8
yakra_box_min_level = 18
yakra_box_min_techlevel = 3
minimum_recruits = false
scale_level_to_leader = true
scale_techlevel_to_leader = true
scale_gear = true
loot_pool = "vanilla"
loot_assignment_scheme = "shuffle"
good_loot_spots = [ "black_omen_royal_path", "black_omen_martello", "black_omen_alien_ne", "black_omen_terra_w", "guardia_forest_sealed_600", "denadoro_mts_speed_tab", "tomas_grave_speed_tab", "medina_elder_speed_tab", "geno_dome_labs_speed_tab", "enhasa_nu_battle_speed_tab", "kajar_speed_tab",]
good_loot = [ "speed_tab",]
good_loot_rate = 1.0
good_loot_2 = [ "power_tab",]
good_loot_spots_2 = [ "zenan_bridge_chef_tab", "guardia_forest_power_tab_600", "guardia_forest_power_tab_1000", "manoria_confinement_power_tab", "porre_market_600_power_tab", "giants_claw_caverns_power_tab", "giants_claw_entrance_power_tab", "giants_claw_traps_power_tab", "sun_keep_600_power_tab", "arris_dome_sealed_power_tab", "death_peak_power_tab", "geno_dome_corridor_power_tab", "sunken_desert_power_tab", "beast_nest_power_tab", "proto_dome_portal_tab", "northern_ruins_landing_power_tab", "johnny_race_power_tab",]
good_loot_rate_2 = 1.0
good_loot_3 = [ "magic_tab",]
good_loot_spots_3 = [ "dorino_bromide_magic_tab", "medina_elder_magic_tab", "magus_castle_flea_magic_tab", "magus_castle_dungeons_magic_tab", "trann_dome_sealed_magic_tab", "blackbird_ducts_magic_tab", "keepers_dome_magic_tab", "geno_dome_atropos_magic_tab", "geno_dome_labs_magic_tab", "enhasa_nu_battle_magic_tab", "kajar_nu_scratch_magic_tab", "last_village_nu_shop_magic_tab", "mountains_re_nice_magic_tab", "mt_woe_magic_tab", "ocean_palace_elevator_magic_tab", "ozzies_fort_guillotines_tab", "northern_ruins_heros_grave_magic_tab",]
good_loot_rate_3 = 1.0
good_loot_4 = [ "blue_rock", "gold_rock", "black_rock", "white_rock", "silverrock",]
good_loot_spots_4 = [ "denadoro_rock", "kajar_rock", "laruba_rock", "black_omen_terra_rock", "giants_claw_rock",]
good_loot_rate_4 = 1.0
good_loot_5 = [ "rainbow", "valkerye", "wondershot", "crisis_arm", "bravesword", "bronzefist", "doomsickle", "safe_helm", "haste_helm", "prism_helm", "vigil_hat", "zodiaccape", "nova_armor", "prismdress", "gloom_helm", "taban_suit", "moon_armor", "prismspecs", "sun_shades",]
good_loot_spots_5 = [ "ozzies_fort_final_1", "yakra_key_chest", "ozzies_fort_final_2", "melchior_sunstone_rainbow", "melchior_rainbow_shell", "melchior_sunstone_specs", "lucca_wondershot", "taban_sunshades", "ozzies_fort_guillotines_4",]
good_loot_rate_5 = 1.0
guaranteed_loot = [ "prism_helm", "prism_helm", "prism_helm", "bronzefist", "prismdress", "iron_fist",]
post_assign_shuffle_rate = 0.5
trading_post_base_cost = 3
trading_post_upgrade_cost = 6
trading_post_special_cost = 9
johnny_key_threshold = 200
johnny_low_threshold = 100
johnny_low_item = "speed_tab"
johnny_low_quantity = 1
johnny_mid_threshold = 700
johnny_mid_item = "speed_tab"
johnny_mid_quantity = 3
johnny_high_threshold = 1200
johnny_high_item = "haste_helm"
johnny_high_quantity = 1
sightscope_all = true
forced_sightscope = true
shuffle_enemies = true
ds_item_pool = [ "dreamseeker", "dragon_arm", "dinoblade", "turboshot", "dreamreaper", "reptite_dress", "dragon_armor", "regal_plate", "regal_gown", "elemental_aegis", "saurian_leathers", "dragonhead", "reptite_tiara", "masters_crown", "angels_tiara", "valor_crest", "dragons_tear", "champions_badge",]
ds_replacement_chance = 50
bronze_fist_policy = "random_other"
weapon_rando_pool = [ "rainbow", "shiva_edge", "terra_arm", "crisis_arm", "masamune_2", "bravesword", "iron_fist", "bronzefist", "starscythe", "doomsickle", "wondershot", "shock_wave", "valkerye", "siren",]
weapon_rando_effect_scheme = "random"
weapon_rando_stat_boost_scheme = "random"
forced_weapon_effects = [ "wonder", "doom", "crisis", "4x_crit", "crisis_mp", "valiant", "mp_crit4x",]
forced_weapon_stat_boosts = [ "magic_6", "magic_10", "power_10", "power_stamina_10", "power_6", "speed_power_3", "speed_3",]
random_weapon_effect_spec = "12: [wonder, doom, crisis, hp_leech_10, mp_leech_5, 4x_crit], 5: [crisis_mp, valiant, 777_dmg, mp_crit4x], 1: 9999_crit"
random_weapon_stat_boost_spec = "20: no_change, 15: [stamina_2, hit_2, magic_2, power_2],10: [stamina_6, power_4, magic_4, hit_10, speed_1],5: [power_stamina_10, speed_2, magic_10],1: [speed_3]"
weapon_rando_pool_2 = [ "mop",]
weapon_rando_effect_scheme_2 = "random"
weapon_rando_stat_boost_scheme_2 = "random"
forced_weapon_effects_2 = []
forced_weapon_stat_boosts_2 = []
random_weapon_effect_spec_2 = "1: [wonder, doom, crisis, hp_leech_10, mp_leech_5, 4x_crit, 777_dmg, crisis_mp,    valiant, mp_crit, mp_crit4x, 9999_crit]"
random_weapon_stat_boost_spec_2 = "1: [   speed_3,   magic_10, power_10, speed_power_3]"
weapon_rando_pool_3 = [ "wood_sword", "iron_blade", "steelsaber", "lode_sword", "red_katana", "flint_edge", "dark_saber", "aeon_blade", "demon_edge", "alloyblade", "star_sword", "vedicblade", "kali_blade", "bolt_sword", "slasher", "bronze_bow", "iron_bow", "lode_bow", "robin_bow", "sage_bow", "dream_bow", "cometarrow", "sonicarrow", "air_gun", "dart_gun", "auto_gun", "picomagnum", "plasma_gun", "ruby_gun", "dream_gun", "megablast", "graedus", "tin_arm", "hammer_arm", "miragehand", "stone_arm", "doomfinger", "magma_hand", "megatonarm", "big_hand", "kaiser_arm", "giga_arm", "bronzeedge", "iron_sword", "masamune_1", "flashblade", "pearl_edge", "rune_blade", "demon_hit", "fist_3", "darkscythe", "hurricane", "swallow", "slasher_2",]
weapon_rando_effect_scheme_3 = "random"
weapon_rando_stat_boost_scheme_3 = "random"
forced_weapon_effects_3 = []
forced_weapon_stat_boosts_3 = []
random_weapon_effect_spec_3 = "50: no_change,15: [stop_60, slow_60, chaos_80,stop_80_machines, mp_leech_2, hp_leech_5],10: [wonder, doom, 4x_crit, valiant, mp_crit, mp_leech_5, hp_leech_10],4: [mp_crit4x, crisis_mp, crisis],1: [9999_crit, 777_dmg]"
random_weapon_stat_boost_spec_3 = "50: no_change,15: [speed_1, hit_2, power_2, stamina_2, magic_2],12: [hit_10, power_4, speed_2, stamina_6, magic_4],10: [mdef_5, speed_3, power_6, magic_6,  magic_mdef_5],5: [mdef_10, power_stamina_10, magic_10, power_10, speed_power_3]"
use_phys_marle = true
use_haste_all = true
use_phys_lucca = true
use_protect_all = true
use_reraise = false
use_magus_dual_techs = true
use_daltonized_magus = false
dalton_level = 30
dalton_plus_level = 22
elder_spawn_level = 47
flea_level = 19
giga_mutant_level = 49
golem_level = 30
golem_boss_level = 34
heckran_level = 14
lavos_spawn_level = 33
mammon_machine_level = 44
magus_nc_level = 31
masa_mune_level = 16
mega_mutant_level = 46
mud_imp_level = 32
nizbel_level = 19
nizbel_2_level = 23
retinite_level = 30
r_series_level = 7
rust_tyrano_level = 38
slash_level = 20
son_of_sun_level = 44
terra_mutant_level = 49
yakra_level = 6
yakra_xiii_level = 42
zombor_level = 10
dragon_tank_level = 6
giga_gaia_level = 32
guardian_level = 7
magus_level = 20
black_tyrano_level = 22
ozzie_trio_level = 34
atropos_level = 40
flea_plus_level = 27
super_slash_level = 27
krawlie_level = 7
gato_level = 1
zeal2_level = 50
plando_recruit_starter = [ "random",]
plando_recruit_cathedral = "random"
plando_recruit_castle = "..."
plando_recruit_millennial_fair = "..."
plando_recruit_dactyl_nest = "..."
plando_recruit_proto_dome = "..."
plando_recruit_frogs_burrow = "..."
plando_recruit_crono_trial = "..."
plando_recruit_death_peak = "random"
plando_recruit_north_cape = "..."
plando_recruit_yakra_box = "none"
equipable_rando_scheme = "vanilla"
input_file = "./ct.sfc"
