xp_scale = 4.0
tp_scale = 6.0
split_tp = false
fix_tp_doubling = true
xp_penalty_level = 45
xp_penalty_percent = 25
level_cap = 50
boss_xp_factor = 1.25
midboss_reward_factor = 1.0
normalize_boss_xp = true
drop_enemy_pool = "vanilla"
drop_reward_pool = "vanilla"
drop_rate = 1.0
custom_drop_enemy_pool = []
drop_enemy_pool_2 = "custom"
drop_reward_pool_2 = "vanilla"
drop_rate_2 = 1.0
custom_drop_enemy_pool_2 = []
drop_enemy_pool_3 = "custom"
drop_reward_pool_3 = "vanilla"
drop_rate_3 = 1.0
custom_drop_enemy_pool_3 = []
drop_enemy_pool_4 = "custom"
drop_reward_pool_4 = "vanilla"
drop_rate_4 = 1.0
custom_drop_enemy_pool_4 = []
mark_dropping_enemies = true
charm_enemy_pool = "all"
charm_reward_pool = "random"
charm_rate = 1.0
custom_charm_enemy_pool = []
charm_enemy_pool_2 = "custom"
charm_reward_pool_2 = "vanilla"
charm_rate_2 = 1.0
custom_charm_enemy_pool_2 = []
charm_enemy_pool_3 = "custom"
charm_reward_pool_3 = "vanilla"
charm_rate_3 = 1.0
custom_charm_enemy_pool_3 = []
charm_enemy_pool_4 = "custom"
charm_reward_pool_4 = "vanilla"
charm_rate_4 = 1.0
custom_charm_enemy_pool_4 = []
mark_charmable_enemies = true
tech_order = "mp_type"
tech_damage = "shuffle"
tech_damage_random_factor_min = 0.75
tech_damage_random_factor_max = 1.25
preserve_magic = false
black_hole_factor = 4.0
black_hole_min = 20.0
show_full_tech_list = true
balance_tech_mps = true
custom_damage_mps = []
normalize_techs = false
dynamic_scaling_scheme = "progression"
levels_per_boss = 3.0
levels_per_quest = 0.0
levels_per_key_item = 0.0
levels_per_objective = 3.0
levels_per_character = 1.0
max_scaling_level = 50
dynamic_scale_lavos = false
dynamic_scale_lavos_gauntlet = false
defense_safety_min_level = 10
defense_safety_max_level = 30
obstacle_safety_level = 30
normal_enemy_hp_scale = 1.0
static_boss_hp_scale = 1.0
static_hp_scale_lavos = false
element_safety_level = 30
millennial_fair_mod = 0
guardia_forest_1000_mod = 0
guardia_forest_600_mod = 0
crono_trial_mod = 0
heckran_cave_mod = 0
truce_canyon_mod = 0
manoria_cathedral_mod = 0
denadoro_mountains_mod = 0
cursed_woods_mod = 0
lab_16_mod = 0
lab_32_mod = 0
sewers_mod = 0
death_peak_mod = 0
arris_dome_mod = 0
proto_dome_mod = 0
factory_ruins_mod = 0
mystic_mountains_mod = 0
hunting_range_mod = 0
dactyl_nest_mod = 0
shell_trial_mod = 0
zenan_bridge_mod = 0
northern_ruins_mod = 0
giants_claw_mod = 0
ozzies_fort_mod = 0
magus_castle_mod = 0
magic_cave_mod = 0
sunken_desert_mod = 0
sun_palace_mod = 0
geno_dome_mod = 0
forest_maze_mod = 0
reptite_lair_mod = 0
tyrano_lair_mod = 0
black_omen_mod = 0
north_cape_mod = 0
epoch_battle_mod = 0
blackbird_mod = 0
enhasa_mod = 0
ocean_palace_mod = 0
mt_woe_mod = 0
additional_key_items = [ "masamune_2",]
forced_spots = []
loose_key_items = [ "sun_stone", "race_log",]
incentive_spots = []
incentive_factor = 5.0
excluded_spots = [ "trading_post_petal_fang_base", "trading_post_petal_fang_upgrade", "trading_post_petal_horn_base", "trading_post_petal_horn_upgrade", "trading_post_petal_feather_base", "trading_post_petal_feather_upgrade", "trading_post_fang_horn_base", "trading_post_fang_horn_upgrade", "trading_post_fang_feather_base", "trading_post_fang_feather_upgrade", "trading_post_horn_feather_base", "trading_post_horn_feather_upgrade", "magus_castle_right_hall", "magus_castle_guillotine_1", "magus_castle_guillotine_2", "magus_castle_slash_room_1", "magus_castle_slash_room_2", "magus_castle_slash_sword_floor", "magus_castle_statue_hall", "magus_castle_four_kids", "magus_castle_ozzie_1", "magus_castle_ozzie_2", "magus_castle_enemy_elevator", "magus_castle_left_hall", "magus_castle_unskippables", "magus_castle_pit_e", "magus_castle_pit_ne", "magus_castle_pit_nw", "magus_castle_pit_w", "magus_castle_flea_magic_tab", "magus_castle_dungeons_magic_tab", "sunken_desert_power_tab", "tyrano_lair_maze_1", "tyrano_lair_maze_2", "tyrano_lair_maze_3", "tyrano_lair_maze_4", "tyrano_lair_throne_1", "tyrano_lair_throne_2", "tyrano_lair_trapdoor", "tyrano_lair_kino_cell", "guardia_jail_fritz_storage", "guardia_jail_cell", "guardia_jail_omnicrone_1", "guardia_jail_omnicrone_2", "guardia_jail_omnicrone_3", "guardia_jail_hole_1", "guardia_jail_hole_2", "guardia_jail_outer_wall", "guardia_jail_omnicrone_4", "prison_tower_1000", "guardia_jail_fritz", "guardia_prison_lunch_bag", "reptite_lair_secret_b2_ne_right", "reptite_lair_secret_b1_sw", "reptite_lair_secret_b1_ne", "reptite_lair_secret_b1_se", "reptite_lair_secret_b2_se_right", "reptite_lair_secret_b2_ne_or_se_left", "reptite_lair_secret_b2_sw", "black_omen_aux_command_mid", "black_omen_aux_command_ne", "black_omen_grand_hall", "black_omen_nu_hall_nw", "black_omen_nu_hall_w", "black_omen_nu_hall_sw", "black_omen_nu_hall_ne", "black_omen_nu_hall_e", "black_omen_nu_hall_se", "black_omen_royal_path", "black_omen_ruminator_parade", "black_omen_eyeball_hall", "black_omen_tubster_fly", "black_omen_martello", "black_omen_alien_sw", "black_omen_alien_ne", "black_omen_alien_nw", "black_omen_terra_w", "black_omen_terra_rock", "black_omen_terra_ne", "ocean_palace_main_s", "ocean_palace_main_n", "ocean_palace_e_room", "ocean_palace_w_room", "ocean_palace_switch_nw", "ocean_palace_switch_sw", "ocean_palace_switch_ne", "ocean_palace_switch_secret", "ocean_palace_final", "ocean_palace_elevator_magic_tab", "blackbird_ducts_magic_tab", "last_village_nu_shop_magic_tab", "toma_reward", "johnny_race_power_tab",]
decay_factor = 0.7
starter_rewards = [ "pacifist", "pacifist",]
out_of_logic_starter_rewards = []
hard_lavos_end_boss = true
boats_of_time = true
jets_of_time = true
min_flight_depth = 0
lock_gates = true
disable_element_locks = false
block_zenan_600 = true
block_zenan_1000 = true
magus_castle_logical_connection = false
boss_randomization_type = "shuffle"
midboss_randomization_type = "shuffle"
vanilla_boss_spots = []
boss_pool = [ "dalton_plus", "flea", "flea_plus", "golem", "golem_boss", "heckran", "masa_mune", "nizbel", "nizbel_2", "rust_tyrano", "slash_sword", "super_slash", "yakra", "yakra_xiii", "zombor", "lavos_spawn", "elder_spawn", "mega_mutant", "giga_mutant", "terra_mutant", "retinite", "son_of_sun", "mother_brain", "guardian", "giga_gaia", "mud_imp", "r_series", "dragon_tank", "zeal", "magus_north_cape",]
midboss_pool = [ "gato", "dalton", "krawlie", "super_slash", "flea_plus", "atropos_xr",]
shop_inventory_randomization = "tiered_random"
shop_capacity_randomization = "vanilla"
not_buyable_items = [ "masamune_1", "masamune_2", "bent_hilt", "bent_sword", "hero_medal", "bike_key", "pendant", "gate_key", "prismshard", "c_trigger", "tools", "jerky", "race_log", "moon_stone", "sun_stone", "ruby_knife", "yakra_key", "clone", "tomas_pop", "pendant_charge", "rainbow_shell", "jetsoftime", "seed", "dreamstone",]
not_sellable_items = [ "masamune_1", "masamune_2", "bent_hilt", "bent_sword", "hero_medal", "petal", "horn", "fang", "feather", "seed", "bike_key", "pendant", "gate_key", "prismshard", "c_trigger", "tools", "jerky", "race_log", "moon_stone", "sun_stone", "ruby_knife", "yakra_key", "clone", "tomas_pop", "petals_2", "fangs_2", "horns_2", "feathers_2", "pendant_charge", "rainbow_shell", "jetsoftime", "dreamstone",]
item_base_prices = "balanced"
item_price_randomization = "random_multiplier"
item_price_min_multiplier = 0.75
item_price_max_multiplier = 2.0
guaranteed_shop_items = []
custom_shop_item_spec = "30: [cons_c], 5: [cons_b], 2: [cons_a], 1:[cons_s], 5: [weapon_d], 10: [weapon_c], 5: [weapon_b], 2: [weapon_a], 1:[weapon_s], 5: [armor_d], 10: [armor_c], 5: [armor_b], 2:[armor_a], 1:[ armor_s], 5: [accessory_d], 10: [accessory_c], 5: [accessory_b], 2:[accessory_a], 1:[accessory_s], 1: [rock], 1: [key_progression], 2: [key_nonprogression],"
show_all_chars_in_shop = false
num_algetty_portal_objectives = 3
num_omen_objectives = 5
num_bucket_objectives = 4
num_gauntlet_objectives = 1
num_timegauge_objectives = 6
no_omen_gauntlet = false
objective_1 = "any_quest"
objective_2 = "any_quest"
objective_3 = "any_quest"
objective_4 = "any_quest"
objective_5 = "any_quest"
objective_6 = "any_quest"
objective_7 = "any_quest"
objective_8 = "any_quest"
shuffle_entrances = true
preserve_spots = [ "manoria_cathedral", "guardia_castle_1000", "millennial_fair", "guardia_castle_600", "cursed_woods", "dactyl_nest", "proto_dome", "north_cape", "death_peak", "heckran_cave", "vortex_pt", "zenan_bridge_600_north", "denadoro_mts", "magus_lair", "arris_dome", "factory_ruins", "northern_ruins_600", "northern_ruins_1000", "giants_claw", "ozzies_fort", "sunken_desert", "sun_palace", "geno_dome", "reptite_lair", "lair_ruins", "terra_cave", "last_village_commons", "zeal_palace", "blackbird", "west_cape", "choras_carpenter_600", "luccas_house", "sun_keep_prehistory", "sun_keep_2300", "porre_mayor_1000", "porre_elder_600", "fionas_villa", "fionas_shrine", "snail_stop", "keepers_dome", "tatas_house",]
rest_vanilla = false
vanilla_spots = []
shuffle_gates = true
separate_gate_eras = false
lair_ruins_default_spot = "last_village_residence"
preserve_spots_1 = []
preserve_spots_2 = []
preserve_spots_3 = []
preserve_spots_4 = []
starter_min_level = 1
starter_min_techlevel = 1
fair_min_level = 1
fair_min_techlevel = 1
cathedral_min_level = 1
cathedral_min_techlevel = 1
castle_min_level = 1
castle_min_techlevel = 1
trial_min_level = 1
trial_min_techlevel = 1
proto_min_level = 1
proto_min_techlevel = 1
north_cape_min_level = 1
north_cape_min_techlevel = 1
burrow_min_level = 1
burrow_min_techlevel = 1
dactyl_min_level = 1
dactyl_min_techlevel = 1
death_peak_min_level = 10
death_peak_min_techlevel = 8
yakra_box_min_level = 25
yakra_box_min_techlevel = 1
minimum_recruits = false
scale_level_to_leader = true
scale_techlevel_to_leader = true
scale_gear = true
loot_pool = "vanilla"
custom_loot_pool = "none"
loot_assignment_scheme = "shuffle"
good_loot = [ "rainbow", "shiva_edge", "swallow", "valkerye", "siren", "wondershot", "taban_suit", "crisis_arm", "terra_arm", "masamune_2", "bronzefist", "doomsickle", "gloom_helm", "gloom_cape", "prism_helm", "vigil_hat", "safe_helm", "haste_helm", "rbow_helm", "mermaidcap", "dark_helm", "moon_armor", "nova_armor", "prismdress", "zodiaccape", "ruby_armor", "prismspecs", "sun_shades", "gold_stud", "gold_erng", "greendream", "blue_rock", "gold_rock", "black_rock", "white_rock", "silverrock", "frenzyband",]
good_loot_spots = [ "enhasa_nu_battle_magic_tab", "denadoro_rock", "dorino_bromide_magic_tab", "arris_dome_sealed_power_tab", "keepers_dome_magic_tab", "trann_dome_sealed_magic_tab", "lab_32_race_log", "hunting_range_nu_reward", "ocean_palace_elevator_magic_tab", "kajar_nu_scratch_magic_tab", "guardia_jail_hole_2", "blackbird_ducts_magic_tab", "zenan_bridge_chef_tab", "lazy_carpenter", "melchior_sunstone_rainbow", "eot_gaspar_reward", "bangor_dome_seal_3", "mt_woe_final_2", "pyramid_right", "pyramid_left", "proto_dome_portal_tab",]
good_loot_rate = 1.0
post_assign_shuffle_rate = 0.5
trading_post_base_cost = 3
trading_post_upgrade_cost = 3
trading_post_special_cost = 10
johnny_key_threshold = 0
johnny_low_threshold = 1200
johnny_low_item = "mid_tonic"
johnny_low_quantity = 5
johnny_mid_threshold = 2000
johnny_mid_item = "ether"
johnny_mid_quantity = 5
johnny_high_threshold = 2300
johnny_high_item = "full_ether"
johnny_high_quantity = 5
use_tech_level_treasures = false
extra_tech_levels_per_char = 0
tech_level_forced_spots = []
guaranteed_loot = []
guaranteed_loot_exact = []
good_loot_2 = []
good_loot_spots_2 = []
good_loot_rate_2 = 0.75
good_loot_3 = []
good_loot_spots_3 = []
good_loot_rate_3 = 0.75
good_loot_4 = []
good_loot_spots_4 = []
good_loot_rate_4 = 0.75
good_loot_5 = []
good_loot_spots_5 = []
good_loot_rate_5 = 0.75
good_loot_6 = []
good_loot_spots_6 = []
good_loot_rate_6 = 0.75
good_loot_7 = []
good_loot_spots_7 = []
good_loot_rate_7 = 0.75
good_loot_8 = []
good_loot_spots_8 = []
good_loot_rate_8 = 0.75
sightscope_all = true
forced_sightscope = true
shuffle_enemies = true
normalize_enemies = false
ds_item_pool = [ "dreamseeker", "venus_bow", "turboshot", "spellslinger", "dragon_arm", "apocalypse_arm", "dinoblade", "judgement_scythe", "dreamreaper", "reptite_dress", "dragon_armor", "regal_plate", "regal_gown", "shadowplume_robe", "elemental_aegis", "saurian_leathers", "dragonhead", "reptite_tiara", "masters_crown", "angels_tiara", "valor_crest", "dragons_tear",]
ds_replacement_chance = 30
bronze_fist_policy = "random_other"
weapon_rando_pool = [ "rainbow", "shiva_edge", "swallow", "slasher", "valkerye", "siren", "sonicarrow", "wondershot", "terra_arm", "crisis_arm", "masamune_1", "masamune_2", "bravesword", "dark_saber", "aeon_blade", "demon_edge", "alloyblade", "star_sword", "vedicblade", "kali_blade", "bolt_sword", "bronze_bow", "iron_bow", "fist", "slasher_2", "mop", "starscythe", "hurricane", "darkscythe", "fist_3", "fist_2", "pearl_edge", "flashblade", "iron_sword", "bronzeedge", "giga_arm", "kaiser_arm", "dream_gun", "big_hand", "megatonarm", "magma_hand", "doomfinger", "stone_arm", "miragehand", "hammer_arm", "tin_arm", "graedus", "shock_wave", "megablast", "ruby_gun", "plasma_gun", "picomagnum", "auto_gun", "dart_gun", "air_gun", "cometarrow", "dream_bow", "sage_bow", "robin_bow", "lode_bow", "rune_blade", "demon_hit", "iron_fist", "bronzefist", "doomsickle", "wood_sword", "iron_blade", "steelsaber", "lode_sword", "flint_edge", "red_katana",]
weapon_rando_effect_scheme = "random"
weapon_rando_stat_boost_scheme = "random"
forced_weapon_effects = [ "wonder", "doom", "crisis", "stop_60", "slow_60", "chaos_80", "stop_80_machines", "4x_crit", "crisis_mp", "valiant", "mp_crit", "mp_crit4x", "9999_crit", "777_dmg", "hp_leech_5", "hp_leech_10", "mp_leech_2", "mp_leech_5",]
forced_weapon_stat_boosts = [ "speed_1", "hit_2", "power_2", "stamina_2", "magic_2", "mdef_5", "speed_3", "hit_10", "power_6", "magic_6", "mdef_10", "power_4", "speed_2", "mdef_20", "stamina_6", "magic_4", "mdef_12", "magic_mdef_5", "power_stamina_10", "mdef_stamina_10", "mdef_9", "magic_10", "power_10", "speed_power_3", "power_5", "magic_5",]
random_weapon_effect_spec = "60: none,20: [stop_60, chaos_80, slow_60],13: [4x_crit, wonder, doom, crisis, crisis_mp],1: [9999_crit, 777_dmg]"
random_weapon_stat_boost_spec = "50: none,20: [stamina_2, hit_2, magic_2, power_2],15: [stamina_6, power_4, magic_4, hit_10, mdef_5, speed_1],5: [power_stamina_10, mdef_stamina_10, mdef_12, speed_2, magic_10],1: [speed_3, mdef_20]"
weapon_rando_pool_2 = []
weapon_rando_effect_scheme_2 = "random"
weapon_rando_stat_boost_scheme_2 = "random"
forced_weapon_effects_2 = []
forced_weapon_stat_boosts_2 = []
random_weapon_effect_spec_2 = "80: none,15: [stop_60, chaos_80, slow_60],4: [4x_crit, wonder, doom, crisis, crisis_mp],1: [9999_crit, 777_dmg]"
random_weapon_stat_boost_spec_2 = "64: none,20: [stamina_2, hit_2, magic_2, power_2],10: [stamina_6, power_4, magic_4, hit_10, mdef_5, speed_1],5: [power_stamina_10, mdef_stamina_10, mdef_12, speed_2, magic_10],1: [speed_3, mdef_20]"
weapon_rando_pool_3 = []
weapon_rando_effect_scheme_3 = "random"
weapon_rando_stat_boost_scheme_3 = "random"
forced_weapon_effects_3 = []
forced_weapon_stat_boosts_3 = []
random_weapon_effect_spec_3 = "80: none,15: [stop_60, chaos_80, slow_60],4: [4x_crit, wonder, doom, crisis, crisis_mp],1: [9999_crit, 777_dmg]"
random_weapon_stat_boost_spec_3 = "64: none,20: [stamina_2, hit_2, magic_2, power_2],10: [stamina_6, power_4, magic_4, hit_10, mdef_5, speed_1],5: [power_stamina_10, mdef_stamina_10, mdef_12, speed_2, magic_10],1: [speed_3, mdef_20]"
use_phys_marle = false
use_haste_all = false
use_phys_lucca = false
use_protect_all = false
use_reraise = false
use_magus_dual_techs = true
use_daltonized_magus = false
tech_rando_scheme = "chaos_element"
mdef_growth_scale_factor = 1.0
mdef_cap = 99
mdef_levelup_cap = 99
dalton_level = 26
dalton_plus_level = 20
elder_spawn_level = 46
flea_level = 19
giga_mutant_level = 47
golem_level = 27
golem_boss_level = 34
heckran_level = 12
lavos_spawn_level = 32
mammon_machine_level = 44
magus_nc_level = 30
masa_mune_level = 15
mega_mutant_level = 46
mud_imp_level = 29
nizbel_level = 17
nizbel_2_level = 23
retinite_level = 28
r_series_level = 5
rust_tyrano_level = 35
slash_level = 20
son_of_sun_level = 43
terra_mutant_level = 48
yakra_level = 4
yakra_xiii_level = 39
zombor_level = 9
dragon_tank_level = 5
giga_gaia_level = 30
guardian_level = 6
magus_level = 20
black_tyrano_level = 20
ozzie_trio_level = 33
atropos_level = 33
flea_plus_level = 27
super_slash_level = 27
krawlie_level = 6
gato_level = 1
zeal2_level = 50
plando_recruit_starter = [ "random",]
plando_recruit_cathedral = "..."
plando_recruit_castle = "..."
plando_recruit_millennial_fair = "..."
plando_recruit_dactyl_nest = "..."
plando_recruit_proto_dome = "..."
plando_recruit_frogs_burrow = "..."
plando_recruit_crono_trial = "..."
plando_recruit_death_peak = "..."
plando_recruit_north_cape = "..."
plando_recruit_yakra_box = "..."
equipable_rando_scheme = "random_all"
crono_lose_equip_normal_percent = 0
marle_lose_equip_normal_percent = 0
lucca_lose_equip_normal_percent = 0
robo_lose_equip_normal_percent = 0
frog_lose_equip_normal_percent = 0
ayla_lose_equip_normal_percent = 0
magus_lose_equip_normal_percent = 0
crono_gain_equip_dress_percent = 0
crono_lose_equip_dress_percent = 0
marle_gain_equip_dress_percent = 0
marle_lose_equip_dress_percent = 0
lucca_gain_equip_dress_percent = 0
lucca_lose_equip_dress_percent = 0
robo_gain_equip_dress_percent = 0
robo_lose_equip_dress_percent = 0
frog_gain_equip_dress_percent = 0
frog_lose_equip_dress_percent = 0
ayla_gain_equip_dress_percent = 0
ayla_lose_equip_dress_percent = 0
magus_gain_equip_dress_percent = 0
magus_lose_equip_dress_percent = 0
crono_gain_equip_heavy_armor_percent = 0
crono_lose_equip_heavy_armor_percent = 0
marle_gain_equip_heavy_armor_percent = 0
marle_lose_equip_heavy_armor_percent = 0
lucca_gain_equip_heavy_armor_percent = 0
lucca_lose_equip_heavy_armor_percent = 0
robo_gain_equip_heavy_armor_percent = 0
robo_lose_equip_heavy_armor_percent = 0
frog_gain_equip_heavy_armor_percent = 0
frog_lose_equip_heavy_armor_percent = 0
ayla_gain_equip_heavy_armor_percent = 0
ayla_lose_equip_heavy_armor_percent = 0
magus_gain_equip_heavy_armor_percent = 0
magus_lose_equip_heavy_armor_percent = 0
crono_gain_equip_personal_percent = 0
crono_lose_equip_personal_percent = 0
marle_gain_equip_personal_percent = 0
marle_lose_equip_personal_percent = 0
lucca_gain_equip_personal_percent = 0
lucca_lose_equip_personal_percent = 0
robo_gain_equip_personal_percent = 0
robo_lose_equip_personal_percent = 0
frog_gain_equip_personal_percent = 0
frog_lose_equip_personal_percent = 0
ayla_gain_equip_personal_percent = 0
ayla_lose_equip_personal_percent = 0
magus_gain_equip_personal_percent = 0
magus_lose_equip_personal_percent = 0
crono_can_equip_percent = 50
marle_can_equip_percent = 50
lucca_can_equip_percent = 50
robo_can_equip_percent = 50
frog_can_equip_percent = 50
ayla_can_equip_percent = 50
magus_can_equip_percent = 50
