"""Keep Track of Location Exit Data"""
from dataclasses import dataclass
import enum

from ctrando.common.ctenums import LocID
from ctrando.locations.locationevent import FunctionID as FID

@dataclass
class LocExitInfo:
    loc_id: LocID
    index: int = 0


@dataclass
class ScriptExitInfo:
    loc_id: LocID
    obj_id: int
    func_id: FID
    cmd_id: int = 0


class LocOWExits(enum.Enum):
    # 1000 AD
    HECKRAN_CAVE_WHIRLPOOL = ScriptExitInfo(LocID.HECKRAN_CAVE_BOSS, 1, FID.ACTIVATE)
    NORTHERN_RUINS_1000 = ScriptExitInfo(LocID.NORTHERN_RUINS_ENTRANCE, 0, FID.STARTUP, 0)
    FIONAS_SHRINE = LocExitInfo(LocID.FIONAS_SHRINE)
    FIONAS_SHRINE_FOREST = ScriptExitInfo(LocID.FIONA_FOREST, 2, FID.ACTIVATE)
    CRONOS_HOUSE = LocExitInfo(LocID.CRONOS_KITCHEN)
    TRUCE_SINGLE_RESIDENCE = LocExitInfo(LocID.TRUCE_SINGLE_WOMAN_RESIDENCE)
    TRUCE_INN_1000 = LocExitInfo(LocID.TRUCE_INN_1000)
    TRUCE_TICKET_OFFICE = LocExitInfo(LocID.TRUCE_TICKET_OFFICE)
    TRUCE_SCREAMING_RESIDENCE = LocExitInfo(LocID.TRUCE_HAPPY_SCREAMING_COUPLE_RESIDENCE)
    MILLENNIAL_FAIR = LocExitInfo(LocID.MILLENNIAL_FAIR)
    TRUCE_MARKET_1000 = LocExitInfo(LocID.TRUCE_MARKET)
    TRUCE_MAYOR = LocExitInfo(LocID.TRUCE_MAYOR_1F)
    LUCCAS_HOUSE = LocExitInfo(LocID.LUCCAS_WORKSHOP)
    LUCCAS_HOUSE_SUNSTONE = ScriptExitInfo(LocID.LUCCAS_WORKSHOP, 3, FID.ARBITRARY_1)
    GUARDIA_CASTLE_1000 = LocExitInfo(LocID.GUARDIA_THRONEROOM_1000)
    GUARDIA_CASTLE_1000_CRONO_TRIAL = ScriptExitInfo(LocID.GUARDIA_THRONEROOM_1000, 0x11, FID.STARTUP )
    GUARDIA_FOREST_SOUTH_1000 = LocExitInfo(LocID.GUARDIA_FOREST_1000, 1)
    GUARDIA_FOREST_NORTH_1000 = LocExitInfo(LocID.GUARDIA_FOREST_1000, 2)
    ZENAN_BRIDGE_1000_NORTH = LocExitInfo(LocID.ZENAN_BRIDGE_1000, 1)
    ZENAN_BRIDGE_1000_SOUTH = LocExitInfo(LocID.ZENAN_BRIDGE_1000, 0)
    PORRE_INN_1000 = LocExitInfo(LocID.PORRE_INN)
    PORRE_MARKET_1000 = LocExitInfo(LocID.PORRE_MARKET_1000)
    PORRE_TICKET_OFFICE = LocExitInfo(LocID.PORRE_TICKET_OFFICE)
    SNAIL_STOP = LocExitInfo(LocID.SNAIL_STOP)
    PORRE_MAYOR_1000 = LocExitInfo(LocID.PORRE_MAYOR_1F)
    PORRE_RESIDENCE_1000 = LocExitInfo(LocID.PORRE_RESIDENCE_1000)
    MEDINA_ELDER = LocExitInfo(LocID.MEDINA_ELDER_1F)
    MEDINA_INN = LocExitInfo(LocID.MEDINA_INN)
    MEDINA_PORTAL = LocExitInfo(LocID.MEDINA_PORTAL)
    MELCHIORS_HUT = LocExitInfo(LocID.MELCHIORS_KITCHEN)
    MEDINA_MARKET = LocExitInfo(LocID.MEDINA_MARKET)
    MEDINA_SQUARE = LocExitInfo(LocID.MEDINA_SQUARE)
    CHORAS_MAYOR_1000 = LocExitInfo(LocID.CHORAS_MAYOR_1F)
    CHORAS_INN_1000 = LocExitInfo(LocID.CHORAS_INN_1000)
    CHORAS_CARPTENTER_1000 = LocExitInfo(LocID.CHORAS_CARPENTER_1000)
    FOREST_RUINS = LocExitInfo(LocID.FOREST_RUINS)
    HECKRAN_CAVE = LocExitInfo(LocID.HECKRAN_CAVE_ENTRANCE)
    SUN_KEEP_1000 = LocExitInfo(LocID.SUN_KEEP_1000)
    WEST_CAPE = LocExitInfo(LocID.WEST_CAPE)
    # 600 AD
    ZENAN_BRIDGE_600_SOUTH = LocExitInfo(LocID.ZENAN_BRIDGE_600, 1)
    ZENAN_BRIDGE_600_NORTH = LocExitInfo(LocID.ZENAN_BRIDGE_600, 0)
    ZENAN_BRIDGE_600_SOUTH_BOSS = LocExitInfo(LocID.ZENAN_BRIDGE_BOSS, 1)
    ZENAN_BRIDGE_600_NORTH_BOSS = LocExitInfo(LocID.ZENAN_BRIDGE_BOSS, 0)
    MAGIC_CAVE_CLOSED = LocExitInfo(LocID.MAGIC_CAVE_EXTERIOR)
    MAGIC_CAVE_OPEN = LocExitInfo(LocID.MAGIC_CAVE_EXTERIOR_OPEN)
    SUNKEN_DESERT_ENTRANCE = LocExitInfo(LocID.SUNKEN_DESERT_ENTRANCE)
    SUNKEN_DESERT_INTERIOR = LocExitInfo(LocID.SUNKEN_DESERT_PARASITES)
    NORTHERN_RUINS_600 = ScriptExitInfo(LocID.NORTHERN_RUINS_ENTRANCE, 0, FID.STARTUP, 1)
    MAGUS_LAIR = LocExitInfo(LocID.MAGUS_CASTLE_EXTERIOR)
    MAGUS_LAIR_END_SCENE_EPOCH = ScriptExitInfo(LocID.MAGUS_CASTLE_INNER_SANCTUM, 9, FID.ACTIVATE, 0)
    MAGUS_LAIR_END_SCENE_NO_EPOCH = ScriptExitInfo(LocID.MAGUS_CASTLE_INNER_SANCTUM, 9, FID.ACTIVATE, 1)
    GIANTS_CLAW = LocExitInfo(LocID.GIANTS_CLAW_ENTRANCE)
    GIANTS_CLAW_END = ScriptExitInfo(LocID.GIANTS_CLAW_TYRANO, 1, FID.STARTUP)
    TRUCE_CANYON = LocExitInfo(LocID.TRUCE_CANYON)
    TRUCE_COUPLE_RESIDENCE_600 = LocExitInfo(LocID.TRUCE_COUPLE_RESIDENCE_600)
    TRUCE_SMITH_RESIDENCE = LocExitInfo(LocID.TRUCE_SMITHY_RESIDENCE_600)
    TRUCE_INN_600 = LocExitInfo(LocID.TRUCE_INN_600_1F)
    TRUCE_MARKET_600 = LocExitInfo(LocID.TRUCE_MARKET_600)
    GUARDIA_FOREST_NORTH_600 = LocExitInfo(LocID.GUARDIA_FOREST_600, 1)
    GUARDIA_FOREST_SOUTH_600 = LocExitInfo(LocID.GUARDIA_FOREST_600, 0)
    GUARDIA_CASTLE_600 = LocExitInfo(LocID.GUARDIA_THRONEROOM_600, 0)
    MANORIA_CATHEDRAL = LocExitInfo(LocID.MANORIA_SANCTUARY)
    MANORIA_END_SCENE = ScriptExitInfo(LocID.MANORIA_COMMAND, 0xC, FID.ACTIVATE)
    DORINO_BROMIDE_RESIDENCE = LocExitInfo(LocID.DORINO_PERVERT_RESIDENCE)
    DORINO_ELDER = LocExitInfo(LocID.DORINO_ELDER_HOUSE)
    DORINO_INN = LocExitInfo(LocID.DORINO_INN)
    DORINO_MARKET = LocExitInfo(LocID.DORINO_MARKET)
    TATAS_HOUSE = LocExitInfo(LocID.TATAS_HOUSE_1F)
    PORRE_ELDER_600 = LocExitInfo(LocID.PORRE_ELDER)
    PORRE_CAFE_600 = LocExitInfo(LocID.PORRE_CAFE_600)
    PORRE_INN_600 = LocExitInfo(LocID.PORRE_INN_600)
    PORRE_MARKET_600 = LocExitInfo(LocID.PORRE_MARKET_600)
    FIONAS_VILLA = LocExitInfo(LocID.FIONAS_VILLA)
    FIONAS_VILLA_TURN_IN = ScriptExitInfo(LocID.FIONAS_VILLA, 8, FID.ACTIVATE)
    CHORAS_OLD_RESIDENCE_600 = LocExitInfo(LocID.CHORAS_600_OLD_COUPLE_RESIDENCE)
    CHORAS_INN_600 = LocExitInfo(LocID.CHORAS_600_INN)
    CHORAS_CAFE_600 = LocExitInfo(LocID.CHORAS_CAFE)
    CHORAS_CARPTENTER_600 = LocExitInfo(LocID.CHORAS_600_CARPENTER_RESIDENCE_1F)
    CHORAS_MARKET_600 = LocExitInfo(LocID.CHORAS_600_MARKET)
    CURSED_WOODS = LocExitInfo(LocID.CURSED_WOODS)
    DENADORO_MTS = LocExitInfo(LocID.DENADORO_ENTRANCE, 3)
    DENADORO_WIND = ScriptExitInfo(LocID.DENADORO_CAVE_OF_MASAMUNE, 0xA, FID.TOUCH)
    MAGIC_CAVE_MAGUS = LocExitInfo(LocID.MAGIC_CAVE_INTERIOR)
    OZZIES_FORT = LocExitInfo(LocID.OZZIES_FORT_ENTRANCE)
    OZZIES_FORT_END = ScriptExitInfo(LocID.OZZIES_FORT_THRONE_INCOMPETENCE, 0x8, FID.TOUCH)
    SUN_KEEP_600 = LocExitInfo(LocID.SUN_KEEP_600)
    # Future
    TRANN_DOME = LocExitInfo(LocID.TRANN_DOME)
    BANGOR_DOME = LocExitInfo(LocID.BANGOR_DOME)
    ARRIS_DOME = LocExitInfo(LocID.ARRIS_DOME)
    ARRIS_DOME_SCRIPT_1 = ScriptExitInfo(LocID.ARRIS_DOME, 9, FID.TOUCH)
    ARRIS_DOME_SCRIPT_2 = ScriptExitInfo(LocID.ARRIS_DOME, 0xA, FID.TOUCH)
    PROTO_DOME = LocExitInfo(LocID.PROTO_DOME)
    KEEPERS_DOME = LocExitInfo(LocID.KEEPERS_DOME)
    FACTORY_RUINS = LocExitInfo(LocID.FACTORY_RUINS_ENTRANCE)
    FACTORY_RUINS_END_SCENE = ScriptExitInfo(  # Changed by basepatch
        LocID.FACTORY_RUINS_SECURITY_CENTER, 0x01, FID.ARBITRARY_0)
    LAB_16_WEST = LocExitInfo(LocID.LAB_16_WEST)
    LAB_16_EAST = LocExitInfo(LocID.LAB_16_EAST)
    LAB_32_WEST = LocExitInfo(LocID.LAB_32_WEST)
    LAB_32_EAST = LocExitInfo(LocID.LAB_32_EAST)
    SEWER_ACCESS_ARRIS = LocExitInfo(LocID.SEWERS_B1, 0)
    SEWER_ACCESS_KEEPERS = LocExitInfo(LocID.SEWERS_B1, 1)
    DEATH_PEAK_FALL = ScriptExitInfo(LocID.DEATH_PEAK_ENTRANCE, 0, FID.STARTUP, 0)
    DEATH_PEAK = ScriptExitInfo(LocID.DEATH_PEAK_ENTRANCE, 0, FID.STARTUP, 1)
    DEATH_PEAK_END_NORECRUIT = ScriptExitInfo(LocID.DEATH_PEAK_SUMMIT, 0, FID.STARTUP)
    DEATH_PEAK_END_RECRUIT = ScriptExitInfo(LocID.DEATH_PEAK_SUMMIT_AFTER, 0, FID.STARTUP)
    SUN_KEEP_2300 = LocExitInfo(LocID.SUN_KEEP_2300)
    GENO_DOME = LocExitInfo(LocID.GENO_DOME_ENTRANCE)
    GENO_DOME_END_SCENE = ScriptExitInfo(LocID.GENO_DOME_MAINFRAME, 0x1E, FID.STARTUP)
    SUN_PALACE = LocExitInfo(LocID.SUN_PALACE)
    # Prehistory
    MYSTIC_MTS = LocExitInfo(LocID.MYSTIC_MTN_GULCH)
    TYRANO_LAIR = LocExitInfo(LocID.TYRANO_LAIR_ENTRANCE)
    TYRANO_LAIR_END_SCENE = ScriptExitInfo(
        LocID.TYRANO_LAIR_KEEP, 0x15, FID.ARBITRARY_0
    )
    FOREST_MAZE_NORTH = LocExitInfo(LocID.FOREST_MAZE, 0)
    FOREST_MAZE_SOUTH = LocExitInfo(LocID.FOREST_MAZE, 1)
    REPTITE_LAIR = LocExitInfo(LocID.REPTITE_LAIR_ENTRANCE)
    REPTITE_LAIR_BACK = LocExitInfo(LocID.REPTITE_LAIR_AZALA_ROOM)
    # I removed this forced transition I guess.
    # REPTITE_LAIR_END_SCENE = ScriptExitInfo(LocID.REPTITE_LAIR_AZALA_ROOM, 0, FID.STARTUP)
    DACTYL_NEST = LocExitInfo(LocID.DACTYL_NEST_LOWER)
    DACTYL_NEST_END_SCENE = ScriptExitInfo(LocID.DACTYL_NEST_SUMMIT, 0, FID.STARTUP)
    SUN_KEEP_PREHISTORY = LocExitInfo(LocID.SUN_KEEP_65MBC)
    IOKA_MEETING_SOUTH = LocExitInfo(LocID.IOKA_MEETING_SITE, 0)
    IOKA_MEETING_NORTH = LocExitInfo(LocID.IOKA_MEETING_SITE, 1)
    CHIEFS_HUT = LocExitInfo(LocID.IOKA_CHIEFS_HUT)
    TRADING_POST = LocExitInfo(LocID.IOKA_TRADING_POST)
    IOKA_SW_HUT = LocExitInfo(LocID.IOKA_SOUTHWEST_HUT)
    IOKA_SWEET_WATER_HUT = LocExitInfo(LocID.IOKA_SWEETWATER_HUT)
    HUNTING_RANGE = LocExitInfo(LocID.HUNTING_RANGE)
    LARUBA_RUINS = LocExitInfo(LocID.LARUBA_RUINS)
    LAIR_RUINS = LocExitInfo(LocID.LAIR_RUINS_PORTAL)
    # Dark Ages
    TERRA_CAVE = LocExitInfo(LocID.ALGETTY_ENTRANCE)
    MT_WOE_END_SCENE = ScriptExitInfo(LocID.MT_WOE_SUMMIT, 0x8, FID.ACTIVATE)
    SKYWAY_ENHASA_SOUTH = LocExitInfo(LocID.SKYWAY_ENHASA_S)
    SKYWAY_ENHASA_NORTH = LocExitInfo(LocID.SKYWAY_ENHASA_N)
    SKYWAY_KAJAR = LocExitInfo(LocID.SKYWAY_KAJAR)
    DARK_AGES_PORTAL_DEFAULT = ScriptExitInfo(LocID.DARK_AGES_PORTAL, 0, FID.STARTUP, 0)
    DARK_AGES_PORTAL_CHOICE = ScriptExitInfo(LocID.DARK_AGES_PORTAL, 0, FID.STARTUP, 1)
    # Zeal
    ZEAL_TELEPORTER_BOTTOM = LocExitInfo(LocID.ZEAL_TELEPORTERS, 0)
    ZEAL_TELEPORTER_TOP = LocExitInfo(LocID.ZEAL_TELEPORTERS, 2)
    ZEAL_PALACE = LocExitInfo(LocID.ZEAL_PALACE)
    ENHASA = LocExitInfo(LocID.ENHASA)
    LAND_BRIDGE_ENHASA_NORTH = LocExitInfo(LocID.LAND_BRIDGE_ENHASA_N)
    LAND_BRIDGE_ENHASA_SOUTH = LocExitInfo(LocID.LAND_BRIDGE_ENHASA_S)
    LAND_BRIDGE_KAJAR = LocExitInfo(LocID.LAND_BRIDGE_KAJAR)
    KAJAR = LocExitInfo(LocID.KAJAR)
    BLACKBIRD = LocExitInfo(LocID.BLACKBIRD_SCAFFOLDING)
    # Last
    NORTH_CAPE = LocExitInfo(LocID.NORTH_CAPE)
    LAST_VILLAGE_COMMNONS = LocExitInfo(LocID.LAST_VILLAGE_COMMONS)
    LAST_VILLAGE_EMPTY_HUT = LocExitInfo(LocID.LAST_VILLAGE_EMPTY_HUT)
    LAST_VILLAGE_SHOP = LocExitInfo(LocID.LAST_VILLAGE_SHOP)
    LAST_VILLAGE_RESIDENCE = LocExitInfo(LocID.LAST_VILLAGE_RESIDENCE)
    SUN_KEEP_LAST_VILLAGE = LocExitInfo(LocID.SUN_KEEP_LAST_VILLAGE)
    DARK_AGES_PORTAL_LAST_VILLAGE = ScriptExitInfo(LocID.DARK_AGES_PORTAL, 0, FID.STARTUP, 2)


class PortalExits(enum.Enum):
    TELEPOD_EXHIBIT = ScriptExitInfo(LocID.TELEPOD_EXHIBIT, 0xA, FID.ACTIVATE, 0)
    TRUCE_CANYON = ScriptExitInfo(LocID.TRUCE_CANYON_PORTAL, 0x1, FID.ARBITRARY_4, 0)
    GUARDIA_FOREST = ScriptExitInfo(LocID.GUARDIA_FOREST_DEAD_END, 0x1, FID.STARTUP, 2)
    BANGOR_DOME = ScriptExitInfo(LocID.BANGOR_DOME, 0xB, FID.ACTIVATE, 0)
    MEDINA_CLOSET = ScriptExitInfo(LocID.MEDINA_PORTAL, 0xD, FID.ACTIVATE, 0)
    MYSTIC_MTS = ScriptExitInfo(LocID.MYSTIC_MTN_PORTAL, 0xA, FID.ACTIVATE, 0)
    LAIR_RUINS = ScriptExitInfo(LocID.LAIR_RUINS_PORTAL, 0x9, FID.ACTIVATE, 1)
    DARK_AGES_CAVE = ScriptExitInfo(LocID.DARK_AGES_PORTAL, 0xB, FID.ACTIVATE, 0)
    PROTO_DOME = ScriptExitInfo(LocID.PROTO_DOME_PORTAL, 0xA, FID.ARBITRARY_0, 0)


_loc_exit_classes: tuple[set[LocOWExits], ...] = (
    {LocOWExits.DENADORO_MTS, LocOWExits.DENADORO_WIND},
    {LocOWExits.REPTITE_LAIR_BACK, LocOWExits.REPTITE_LAIR},  # LocOWExits.REPTITE_LAIR_END_SCENE},
    {LocOWExits.MANORIA_CATHEDRAL, LocOWExits.MANORIA_END_SCENE},
    {LocOWExits.FACTORY_RUINS, LocOWExits.FACTORY_RUINS_END_SCENE},
    {LocOWExits.GENO_DOME, LocOWExits.GENO_DOME_END_SCENE},
    {LocOWExits.GIANTS_CLAW, LocOWExits.GIANTS_CLAW_END},
    {LocOWExits.TERRA_CAVE, LocOWExits.MT_WOE_END_SCENE},  # Revisit if Beast Cave gets detached
    {LocOWExits.TYRANO_LAIR, LocOWExits.TYRANO_LAIR_END_SCENE},
    {LocOWExits.MAGUS_LAIR, LocOWExits.MAGUS_LAIR_END_SCENE_EPOCH, LocOWExits.MAGUS_LAIR_END_SCENE_NO_EPOCH},
    {LocOWExits.DEATH_PEAK, LocOWExits.DEATH_PEAK_FALL, LocOWExits.DEATH_PEAK_END_NORECRUIT,
     LocOWExits.DEATH_PEAK_END_RECRUIT},
    {LocOWExits.SUN_KEEP_2300, LocOWExits.LUCCAS_HOUSE_SUNSTONE},
    {LocOWExits.GUARDIA_CASTLE_1000, LocOWExits.GUARDIA_CASTLE_1000_CRONO_TRIAL},
    {LocOWExits.ARRIS_DOME, LocOWExits.ARRIS_DOME_SCRIPT_1, LocOWExits.ARRIS_DOME_SCRIPT_2},
    {LocOWExits.SUNKEN_DESERT_INTERIOR, LocOWExits.SUNKEN_DESERT_ENTRANCE},
    {LocOWExits.DACTYL_NEST, LocOWExits.DACTYL_NEST_END_SCENE},
    {LocOWExits.ZENAN_BRIDGE_600_SOUTH, LocOWExits.ZENAN_BRIDGE_600_NORTH,
     LocOWExits.ZENAN_BRIDGE_600_SOUTH_BOSS, LocOWExits.ZENAN_BRIDGE_600_NORTH_BOSS},
    {LocOWExits.OZZIES_FORT_END, LocOWExits.OZZIES_FORT},
    {LocOWExits.FIONAS_VILLA, LocOWExits.FIONAS_VILLA_TURN_IN},
    {LocOWExits.FIONAS_SHRINE, LocOWExits.FIONAS_SHRINE_FOREST}
)
_exit_class_dict: dict[LocOWExits, set[LocOWExits]] = {
    loc_exit: loc_class
    for loc_class in _loc_exit_classes
    for loc_exit in loc_class
}

def get_loc_exit_class(loc_exit: LocOWExits):
    return _exit_class_dict.get(loc_exit, {loc_exit})
